// AUTO-GENERATED BY @sidebase/nuxt-auth
declare module '#auth' {
  const { getServerSession, getToken, NuxtAuthHandler }: typeof import('/Users/jamesbaddiley/Library/Mobile Documents/com~apple~CloudDocs/Documents/Websites/DIRECTORY/base/node_modules/@sidebase/nuxt-auth/dist/runtime/server/services')
}
