// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/[...]').default>>>>
    }
    '/api/icons': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/icons').default>>>>
    }
    '/api/plugins/db-indexes': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/plugins/db-indexes').default>>>>
    }
    '/api/query/:collection': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/query/[collection].post').default>>>>
    }
    '/api/query/abort': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/query/abort.post').default>>>>
    }
    '/api/query/commit': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/query/commit.post').default>>>>
    }
    '/api/query/session': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/query/session.post').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/query/session').default>>>>
    }
    '/api/test': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/test').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}