// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/28/2025, 8:34:50 AM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/jamesbaddiley/Library/Mobile Documents/com~apple~CloudDocs/Documents/Websites/DIRECTORY/base/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jamesbaddiley/Library/Mobile Documents/com~apple~CloudDocs/Documents/Websites/DIRECTORY/base/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jamesbaddiley/Library/Mobile Documents/com~apple~CloudDocs/Documents/Websites/DIRECTORY/base/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jamesbaddiley/Library/Mobile Documents/com~apple~CloudDocs/Documents/Websites/DIRECTORY/base/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jamesbaddiley/Library/Mobile Documents/com~apple~CloudDocs/Documents/Websites/DIRECTORY/base/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jamesbaddiley/Library/Mobile Documents/com~apple~CloudDocs/Documents/Websites/DIRECTORY/base/plugins/**/*.{js,ts,mjs}","/Users/jamesbaddiley/Library/Mobile Documents/com~apple~CloudDocs/Documents/Websites/DIRECTORY/base/composables/**/**/*.{js,ts,mjs}","/Users/jamesbaddiley/Library/Mobile Documents/com~apple~CloudDocs/Documents/Websites/DIRECTORY/base/utils/**/**/*.{js,ts,mjs}","/Users/jamesbaddiley/Library/Mobile Documents/com~apple~CloudDocs/Documents/Websites/DIRECTORY/base/composables/**/*.{js,ts,mjs}","/Users/jamesbaddiley/Library/Mobile Documents/com~apple~CloudDocs/Documents/Websites/DIRECTORY/base/utils/**/*.{js,ts,mjs}","/Users/jamesbaddiley/Library/Mobile Documents/com~apple~CloudDocs/Documents/Websites/DIRECTORY/base/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/jamesbaddiley/Library/Mobile Documents/com~apple~CloudDocs/Documents/Websites/DIRECTORY/base/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/jamesbaddiley/Library/Mobile Documents/com~apple~CloudDocs/Documents/Websites/DIRECTORY/base/app.config.{js,ts,mjs}","/Users/jamesbaddiley/Library/Mobile Documents/com~apple~CloudDocs/Documents/Websites/DIRECTORY/base/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;