import {join} from 'path';
import {promises as fsPromises} from 'fs';
import {coreServiceLocator} from '../../serviceLocator';
import {ChatGptHelper} from '../../utils';
import {IDataCrud} from '../../db';
import {nodeSystemDataHelper} from '../../db/node-system-data-helper';
import {prepareCompletionBatchItem, storeBatchFile} from './re-build-markets.extras';
const {writeFile, readFile} = fsPromises;


const chatGptHelper = coreServiceLocator.get<ChatGptHelper>('chatGptHelper');
const dataCrudService = coreServiceLocator.get<IDataCrud>('dataCrudService');


const requestMessageList = [
    "Hi ChatGPT. I'm working on the retro cars sales website. I have the vehicle marques list from my DB. Could you please do several things with it:\n- Exclude the duplicate marques (sometimes it's possible to have different namings of the same marques). Please confirm the filtration based on reputable sources such as automotive history databases, brand websites, or Wikipedia. Please keep items separatelly if the company name was actual for some historycal period of time.\nIMPORTANT - Please response JSON array with processed marque names WITHOUT formatting (plain text).\n\nHere's the JSON array with marques from the DB:\n[\"A.J.S.\",\"A.P.C. Motor Company\",\"ABC\",\"AC\",\"ACAM\",\"ACM\",\"ADM\",\"AEC\",\"AFM\",\"AHS\",\"AJS Motorcycles\",\"AK\",\"ALCA\",\"ALPINA\",\"AM General\",\"AMC\",\"AME\",\"AMF Harley-Davidson\",\"AMS\",\"ARO\",\"ASA\",\"ASM\",\"ATK\",\"ATS\",\"AWO (Simson)\",\"AWS\",\"AWZ\",\"Aaglander\",\"Abarth\",\"Abarth-Simca\",\"Ace\",\"Ache Frères\",\"Achilles\",\"Acoma\",\"Acura\",\"Adams\",\"Adler\",\"Adly\",\"Adria\",\"Aeon-Motor\",\"Aermacchi\",\"Aermacchi Harley-Davidson\",\"Aero\",\"Aero Caproni\",\"Agrati\",\"Agrati-Garelli\",\"Agria\",\"Ahrens-Fox\",\"Aiglon\",\"Airstream\",\"Aktiv Fisher\",\"Alba\",\"Albany\",\"Albar\",\"Albion\",\"Alco\",\"Alcyon\",\"Alfa Romeo\",\"Allard\",\"Alldays\",\"Allgaier\",\"Allis Chalmers\",\"Allison\",\"Allright\",\"Allstate\",\"Alma\",\"Alpenkreuzer\",\"Alpenland\",\"Alpenscooter\",\"Alpine\",\"Alpino\",\"Alta\",\"Alvis\",\"American Austin\",\"American Bantam\",\"American IronHorse\",\"American LaFrance\",\"American Motor Car Company\",\"Americar\",\"Amerio\",\"Amilcar\",\"Amphicar\",\"Amphicruiser\",\"Ancillotti\",\"Ancora\",\"Anglia Cars\",\"Ansaldo\",\"Antem\",\"Apal\",\"Apolda\",\"Apollo\",\"Aprilia\",\"Aquila\",\"Arab\",\"Arden\",\"Ardie\",\"Argo\",\"Ariel\",\"Ariel Motor Company\",\"Ariel Motorcycles\",\"Aristocat\",\"Ariès\",\"Arkley\",\"Arlen Ness\",\"Armstrong\",\"Armstrong Siddeley\",\"Armstrong-Siddeley\",\"Arnolt\",\"Arnolt-Bristol\",\"Arnolt-MG\",\"Arnott\",\"Arrows\",\"Artega\",\"Arve\",\"Ascari\",\"Ascari Cars\",\"Ashley Laminates\",\"Asia\",\"Aspes\",\"Aston Martin\",\"Atala\",\"Atalanta\",\"Atterbury\",\"Auburn\",\"Audi\",\"Austermann\",\"Austin\",\"Austin Automobile Company\",\"Austin Motor Company\",\"Austin-Healey\",\"Austro-Daimler\",\"Austro-Tatra\",\"Autech\",\"Auto Mirage\",\"Auto Union\",\"Autobianchi\",\"Autobleu\",\"Autocar\",\"Autokraft\",\"Automobiles Charron, Girardot et Voigt (CGV)\",\"Automobiles Julien\",\"Automobiles Talbot\",\"Automoto\",\"Autovia\",\"Autozam\",\"Autozodiaco\",\"Avante\",\"Avanti\",\"Avanti II\",\"Avinton\",\"Avion\",\"Avions Voisin\",\"Avon\",\"Aztec\"]",
    "Hi ChatGPT. I'm working on the retro cars sales website. I have the vehicle marques list from my DB. Could you please do several things with it:\n- Exclude the duplicate marques (sometimes it's possible to have different namings of the same marques). Please confirm the filtration based on reputable sources such as automotive history databases, brand websites, or Wikipedia. Please keep items separatelly if the company name was actual for some historycal period of time.\nIMPORTANT - Please response JSON array with processed marque names WITHOUT formatting (plain text).\n\nHere's the JSON array with marques from the DB:\n[\"B. F. Meyers & Company\",\"B.N.C.\",\"B.W.A.\",\"BAC\",\"BAC Mono\",\"BAE\",\"BAW\",\"BFG\",\"BIOD\",\"BJR\",\"BM\",\"BMA\",\"BMW\",\"BRA\",\"BRM\",\"BSA\",\"BSW\",\"Babiole\",\"Bacchelli e Villa\",\"Backdraft\",\"Badel\",\"Bailey\",\"Baillou\",\"Bajaj\",\"Baker Electric\",\"Balkan\",\"Ballot\",\"Bandini\",\"Banham\",\"Banjo\",\"Barkas\",\"Baron\",\"Bastei\",\"Bastert\",\"Batavus\",\"Bauer\",\"Baum\",\"Bautz\",\"Bayliss-Thomas\",\"Bean\",\"Beardmore Precision\",\"Beauford\",\"Beck\",\"Bedford\",\"Bedford Vehicles\",\"Behnke\",\"Beijing Automobile Works\",\"Beilharz\",\"Belarus\",\"Belsize\",\"Benelli\",\"Benetton\",\"Benjamin\",\"Benova\",\"Bentley\",\"Benz\",\"Benz & Cie.\",\"Berger\",\"Berkeley\",\"Berliet\",\"Berna\",\"Bernardet\",\"Berneg\",\"Bertone\",\"Beta\",\"Bianchi\",\"Bianco\",\"Bieber\",\"Bimota\",\"Birkin\",\"Bischoff\",\"Biscúter\",\"Bismarck\",\"Bitter\",\"Bizzarrini\",\"Blue Bird\",\"Bobsy\",\"Bohse\",\"Boldmen\",\"Bolinder-Munktell\",\"Bombardier\",\"Bonanza\",\"Bond\",\"Boom\",\"Borghi\",\"Borgward\",\"Borgward-Iso\",\"Bosato Automobili Torino\",\"Boss Hoss\",\"Bourgeois\",\"Bourget\",\"Boursaud\",\"Bowler\",\"Bowler Motors\",\"Bown\",\"Boyer & Cie.\",\"Brabham\",\"Brabus\",\"Bradbury Motor Cycles\",\"Bradley\",\"Brasier\",\"Brasinca\",\"Bremen Sport Equipment\",\"Brennabor\",\"Brewster\",\"Bricklin\",\"Bridgestone Motorcycles\",\"Briggs Cunningham\",\"Brightwheel\",\"Brissonnet\",\"Bristol\",\"British Leyland\",\"Briton\",\"Brixton\",\"Broadspeed\",\"Brockhouse\",\"Brooke\",\"Brough Superior\",\"Brough-Superior\",\"Brunton\",\"Bruseghini\",\"Brändle\",\"Bucci\",\"Bucciali\",\"Bucher\",\"Buckler\",\"Buell\",\"Buell Motorcycle Company\",\"Bufori\",\"Bugatti\",\"Bugnotti\",\"Buick\",\"Bultaco\",\"Bungartz\",\"Burlington\",\"Burton\",\"Byers\",\"Böhmerland\",\"Böhringer\",\"Bücker\",\"Bührer\",\"Bürstner\",\"Büssing\"]",
    "Hi ChatGPT. I'm working on the retro cars sales website. I have the vehicle marques list from my DB. Could you please do several things with it:\n- Exclude the duplicate marques (sometimes it's possible to have different namings of the same marques). Please confirm the filtration based on reputable sources such as automotive history databases, brand websites, or Wikipedia. Please keep items separatelly if the company name was actual for some historycal period of time.\nIMPORTANT - Please response JSON array with processed marque names WITHOUT formatting (plain text).\n\nHere's the JSON array with marques from the DB:\n[\"C.G.V.\",\"CAP\",\"CAV\",\"CCC\",\"CCM\",\"CDL\",\"CERA\",\"CG\",\"CMC\",\"CMP\",\"CN\",\"CR&S\",\"CZ\",\"Cadillac\",\"Cagiva\",\"Caldwell\",\"California Custom Coach\",\"Calthorpe\",\"Cameron\",\"Campagna Motors\",\"Can-Am\",\"Canada Cycle & Motor Company\",\"Cannondale Motorcycles\",\"Capriolo\",\"Caproni-Vizzola\",\"Carabela\",\"Caravelair\",\"Carbodies\",\"Carlsson\",\"Carniel\",\"Carrozzeria Castagna\",\"Carrozzeria Sports Cars\",\"Cartercar\",\"Carver\",\"Casal\",\"Casalini\",\"Case-IH\",\"Castiglioni\",\"Caterham\",\"Ceccato\",\"Ceirano\",\"Cemec\",\"Century Boat Company\",\"Cessna Aircraft Company\",\"Chadwick\",\"Chalmers Motor Company\",\"Chalmers-Detroit\",\"Chamonix NG Cars\",\"Champion\",\"Chandler\",\"Chang Jiang\",\"Charron\",\"Chateau\",\"Chater-Lea\",\"Checker\",\"Cheetah\",\"Chenard - Walcker\",\"Cheney-Triumph\",\"Chesil\",\"Chevrolet\",\"Chevron\",\"Chinook\",\"Chollet\",\"Chris-Craft\",\"Chrysler\",\"Chrysler-Simca\",\"Cimatti\",\"Cisitalia\",\"Citroën\",\"Citroën-Kegresse\",\"Cizeta\",\"Cizeta V16T\",\"Clark Cortez Motorhomes\",\"Classic Motor Carriages\",\"Classic Roadsters\",\"Classic Speed\",\"Clenet\",\"Cleveland\",\"Clyno\",\"Clément Panhard\",\"Clénet\",\"Coachmen\",\"Cobretti\",\"Cockshutt\",\"Colani\",\"Cole Motor Car Company\",\"Columbia\",\"Commer\",\"Compagnie Nationale Excelsior\",\"Condor\",\"Condor BMW\",\"Confederate\",\"Connaught\",\"Constructam\",\"Contemporary Classics\",\"Continent\",\"Cooper\",\"Cooper Car Company\",\"Cord\",\"Corona Brandenburg\",\"Corsar\",\"Corsini\",\"Costin Nathan\",\"Cottereau\",\"Cotton\",\"Courage\",\"Coussement\",\"Coventry Eagle\",\"Coventry-Eagle\",\"Covin\",\"Crane-Simplex\",\"Crawford-Ferrari\",\"Cretors\",\"Croco\",\"Crofton\",\"Croizemarie\",\"Crosley\",\"Crossley\",\"Crosslé\",\"Culebra\",\"Cunningham\",\"Cushman\",\"Cyklon\",\"Cyrus\"]",
    "Hi ChatGPT. I'm working on the retro cars sales website. I have the vehicle marques list from my DB. Could you please do several things with it:\n- Exclude the duplicate marques (sometimes it's possible to have different namings of the same marques). Please confirm the filtration based on reputable sources such as automotive history databases, brand websites, or Wikipedia. Please keep items separatelly if the company name was actual for some historycal period of time.\nIMPORTANT - Please response JSON array with processed marque names WITHOUT formatting (plain text).\n\nHere's the JSON array with marques from the DB:\n[\"D-Rad\",\"D-Rad NSU\",\"DAF\",\"DB (Deutsch-Bonnet)\",\"DINA\",\"DK\",\"DKR\",\"DKW\",\"DKW-Vemag\",\"DMW\",\"DOT\",\"DRK\",\"DUO\",\"Dacia\",\"Dacunha\",\"Daelim\",\"Daewoo\",\"Daihatsu\",\"Daimler\",\"Daimler Company Limited\",\"Dakar\",\"Dallara\",\"Danuvia-Csepel\",\"Dare\",\"Darracq\",\"Datsun\",\"Dauer\",\"David Brown\",\"Davies\",\"Davis\",\"Davrian\",\"Dax\",\"Day-Elder\",\"De Cadenet-Lola\",\"De Dion-Bouton\",\"De La Chapelle\",\"De Reu\",\"De Sanctis\",\"De Tomaso\",\"DeLorean\",\"DeLorean Motor Company\",\"DeSoto\",\"Deetype\",\"Dei\",\"Deidt\",\"Delage\",\"Delahaye\",\"Delaunay-Belleville\",\"Dellow\",\"Delta Motors\",\"Demm\",\"Dennis\",\"Deon\",\"Derbi\",\"Derby\",\"Derby-Ferrari\",\"Derichs\",\"Deronda\",\"Deserter\",\"Dethleffs\",\"Deuliewag\",\"Deutsch-Bonnet\",\"Deutz\",\"Devaux\",\"Devin\",\"Di Blasi\",\"Diamond T\",\"Diatto\",\"Diavolino\",\"Digue\",\"Diva\",\"Divco\",\"Dixi\",\"Dnepr\",\"Dodge\",\"Dollar\",\"Donford\",\"Doniselli\",\"Donkervoort\",\"Donnet-Zedel\",\"Donzi Marine\",\"Dort\",\"Douglas\",\"Dover\",\"Dowsetts\",\"Dresch\",\"Dual-Ghia\",\"Ducati\",\"Ducati Mototrans\",\"Duesenberg\",\"Dune Buggies\",\"Dunham\",\"Dunphy Boat Company\",\"Dunsmore\",\"Dunstall\",\"Duport\",\"Durant\",\"Dutra\",\"Dutton\",\"Dürkopp-Werke\"]",
    "Hi ChatGPT. I'm working on the retro cars sales website. I have the vehicle marques list from my DB. Could you please do several things with it:\n- Exclude the duplicate marques (sometimes it's possible to have different namings of the same marques). Please confirm the filtration based on reputable sources such as automotive history databases, brand websites, or Wikipedia. Please keep items separatelly if the company name was actual for some historycal period of time.\nIMPORTANT - Please response JSON array with processed marque names WITHOUT formatting (plain text).\n\nHere's the JSON array with marques from the DB:\n[\"E-M-F\",\"EBM\",\"EJS\",\"EMF\",\"EMW\",\"ERA\",\"ERF\",\"ESO\",\"ETV\",\"EWB Cars\",\"Eagle\",\"Eagle Manufacturing\",\"Ebro\",\"Ecarrus\",\"Eccles\",\"Eckert-Honda\",\"Edge\",\"Edsel\",\"Edwards\",\"Effeffe\",\"Egli\",\"Egli-Ducati\",\"Egli-Honda\",\"Egli-Kawasaki\",\"Egli-Suzuki\",\"Egli-Vincent\",\"Eicher\",\"Eicker\",\"Eifelland\",\"Eilers\",\"Elan\",\"Elcar\",\"Elddis Autoking\",\"Elden\",\"Elite\",\"Elva\",\"Empolini\",\"Emva\",\"Enfield-Allday\",\"English Mechanic\",\"Ensign\",\"Ensinger\",\"Envemo\",\"Enzmann\",\"Epperly\",\"Eriba\",\"Ermini\",\"Ermini Gilco\",\"Ermolli\",\"Ernst-Werke\",\"Erskine\",\"Es-Ka\",\"Escargot\",\"Essex\",\"Esterel\",\"Eunos\",\"Eura Caravan\",\"EuroBrun\",\"Evans\",\"Evanta\",\"Evante\",\"Everett-Morrison\",\"Ewing\",\"Excalibur\",\"Excelsior\",\"Excelsior Motor Company\",\"Excelsior Motor Manufacturing & Supply Company\",\"Excelsior-Henderson\",\"Express Werke\"]",
    "Hi ChatGPT. I'm working on the retro cars sales website. I have the vehicle marques list from my DB. Could you please do several things with it:\n- Exclude the duplicate marques (sometimes it's possible to have different namings of the same marques). Please confirm the filtration based on reputable sources such as automotive history databases, brand websites, or Wikipedia. Please keep items separatelly if the company name was actual for some historycal period of time.\nIMPORTANT - Please response JSON array with processed marque names WITHOUT formatting (plain text).\n\nHere's the JSON array with marques from the DB:\n[\"F&S\",\"F.I.M.A.\",\"FAMO\",\"FASA-Renault\",\"FAUN\",\"FBW\",\"FFR\",\"FMR TG500\",\"FN\",\"FSC Zuk\",\"FSM\",\"FV Frangivento\",\"Facel Vega\",\"Factory Five\",\"Factory Five Racing\",\"Fafnir\",\"Fahr\",\"Fairthorpe\",\"Faka\",\"Falcon\",\"Falcon Shells\",\"Fantic\",\"Faranda\",\"Farbio\",\"Fargo\",\"Farmall\",\"Favor\",\"Favorit\",\"Federal\",\"Federal Motor Truck Company\",\"Felber\",\"Fendt\",\"Ferguson\",\"Feriela\",\"Ferrari\",\"Ferrario\",\"Ferves\",\"Fiat\",\"Fiatagri\",\"Fiberfab\",\"Fibral\",\"Fichtel & Sachs\",\"Fina Sport\",\"Fiorano\",\"Fischer Kawasaki\",\"Fisher\",\"Fisker\",\"Fittipaldi\",\"Flanders\",\"Fleetwood\",\"Fletcher\",\"Fleur de Lys\",\"Flint\",\"Flottweg\",\"Flxible\",\"Flying Merkel\",\"Focus\",\"Foden\",\"Ford\",\"Fordson\",\"Foreman\",\"Formosa\",\"Formula 27\",\"Fram-King\",\"Framo\",\"Francis Barnett\",\"Francis-Barnett\",\"Franklin\",\"Fratelli Ferrari\",\"Frazer Nash\",\"Freightliner\",\"Frera\",\"Frischauf\",\"Frisky\",\"Fuchs\",\"Fuji\",\"Fuldamobil\",\"Furore\"]",
    "Hi ChatGPT. I'm working on the retro cars sales website. I have the vehicle marques list from my DB. Could you please do several things with it:\n- Exclude the duplicate marques (sometimes it's possible to have different namings of the same marques). Please confirm the filtration based on reputable sources such as automotive history databases, brand websites, or Wikipedia. Please keep items separatelly if the company name was actual for some historycal period of time.\nIMPORTANT - Please response JSON array with processed marque names WITHOUT formatting (plain text).\n\nHere's the JSON array with marques from the DB:\n[\"GAZ\",\"GBS\",\"GFG\",\"GMC\",\"GMG\",\"GN\",\"GP\",\"GRD\",\"GTA\",\"GTD\",\"GTM\",\"Gallina\",\"Ganna\",\"Garanzini\",\"Gardner\",\"Gardner Douglas\",\"Garelli\",\"Garia\",\"GasGas\",\"Gasmobile\",\"Gasser\",\"Gatsby\",\"Gatso\",\"Geier-Werke\",\"Gemballa\",\"Gentry\",\"Geo\",\"Georges Irat\",\"Gerosa\",\"Geser\",\"Ghezzi & Brian\",\"Ghia\",\"Ghostrider Choppers\",\"Giannini\",\"Giaur\",\"Gibbs\",\"Gilbern\",\"Gilco\",\"Gilera\",\"Gillet-Herstal\",\"Gillig\",\"Ginetta\",\"Gitan\",\"Gitane Test\",\"Giulietta\",\"Gladiator\",\"Gladstone\",\"Glas\",\"Glasspar\",\"Gnome et Rhône\",\"Goggomobil\",\"Goliath\",\"Gordini\",\"Gordon-Keeble\",\"Gorgus\",\"Gori\",\"Graham\",\"Graham-Paige\",\"Grandin\",\"Gray-Dort\",\"Grayson\",\"Grecav\",\"Greeves\",\"Griffith\",\"Griffon\",\"Grindlay Peerless\",\"Grinnall\",\"Grisham\",\"Gritzner\",\"Grumman Olson\",\"Gräf & Stift\",\"Grümer\",\"Guazzoni\",\"Gugel\",\"Gulf\",\"Gullwing\",\"Gumpert\",\"Gurgel\",\"Gutbrod\",\"Gwynne\",\"Göricke\",\"Güldner\"]",
    "Hi ChatGPT. I'm working on the retro cars sales website. I have the vehicle marques list from my DB. Could you please do several things with it:\n- Exclude the duplicate marques (sometimes it's possible to have different namings of the same marques). Please confirm the filtration based on reputable sources such as automotive history databases, brand websites, or Wikipedia. Please keep items separatelly if the company name was actual for some historycal period of time.\nIMPORTANT - Please response JSON array with processed marque names WITHOUT formatting (plain text).\n\nHere's the JSON array with marques from the DB:\n[\"HAZ\",\"HE\",\"HELA\",\"HEOS\",\"HKT\",\"HMC\",\"HMO\",\"HMW\",\"HRD\",\"HRG\",\"HTS\",\"HWM\",\"Hadi\",\"Hagedorn\",\"Hahn\",\"Hanomag\",\"Hanomag-Henschel\",\"Hansa\",\"Harlette-Géco\",\"Harley-Davidson\",\"Harlé\",\"Harris-Léon Laisne\",\"Hartge\",\"Hatz\",\"Hawk\",\"Hayden\",\"Haynes\",\"Hazlewood\",\"Healey\",\"Healy\",\"Healy Designs\",\"Hecker\",\"Heidemann\",\"Heine-Velox\",\"Heinkel\",\"Hema\",\"Henderson\",\"Henderson Motorcycle\",\"Henley\",\"Hennessey Performance Engineering\",\"Henney\",\"Henschel\",\"Hercules\",\"Heritage\",\"Heron\",\"Hesketh\",\"Hesketh Motorcycles\",\"Heuliez\",\"Heynsdyk\",\"HiTec\",\"Hiawatha\",\"Hildebrand & Wolfmüller\",\"Hillman\",\"Hillmann\",\"Hindustan\",\"Hino\",\"Hirth\",\"Hispano-Alemán\",\"Hispano-Suiza\",\"Hobart\",\"Hobby\",\"Hodaka\",\"Hoffmann\",\"Holden\",\"Holder\",\"Holman-Moody\",\"Holsman\",\"Hommell\",\"Honda\",\"Hoppe\",\"Horch\",\"Horex\",\"Hosek\",\"Hot Car\",\"Hotchkiss\",\"Hotzenblitz\",\"Hudson\",\"Humber\",\"Humber Limited\",\"Hummel\",\"Hummer\",\"Hupmobile\",\"Huron\",\"Hurtan\",\"Husqvarna\",\"Hustler\",\"Hyde\",\"Hyundai\",\"Hägglunds\",\"Hénon\",\"Hürlimann\"]",
    "Hi ChatGPT. I'm working on the retro cars sales website. I have the vehicle marques list from my DB. Could you please do several things with it:\n- Exclude the duplicate marques (sometimes it's possible to have different namings of the same marques). Please confirm the filtration based on reputable sources such as automotive history databases, brand websites, or Wikipedia. Please keep items separatelly if the company name was actual for some historycal period of time.\nIMPORTANT - Please response JSON array with processed marque names WITHOUT formatting (plain text).\n\nHere's the JSON array with marques from the DB:\n[\"I.S.S.I.\",\"IAME\",\"IFA\",\"IHC\",\"IKA\",\"IKA-Renault\",\"ILO\",\"IMA\",\"IMC\",\"IMV\",\"IMZ-Ural\",\"INEOS\",\"IWL\",\"IZH\",\"Iconic Autobody\",\"Imperia\",\"Imperial\",\"Imperial Automobile Company\",\"Impéria Automobiles\",\"Inbrav\",\"Indian\",\"Indian Motorcycle\",\"Ineos Automotive\",\"Infiniti\",\"Innocenti\",\"Inter-State\",\"Intercamp\",\"Interclassic\",\"Intermeccanica\",\"International\",\"International Harvester\",\"Intramotor Gloria\",\"Invicta\",\"Irmscher\",\"Isdera\",\"Iso\",\"Iso Rivolta\",\"Isotta Fraschini\",\"Isuzu\",\"Itala\",\"Italcaravan\",\"Italdesign Giugiaro\",\"Italjet\",\"Itasca\",\"Itom\",\"Iveco\",\"Iveco Magirus\",\"Ixion\"]",
    "Hi ChatGPT. I'm working on the retro cars sales website. I have the vehicle marques list from my DB. Could you please do several things with it:\n- Exclude the duplicate marques (sometimes it's possible to have different namings of the same marques). Please confirm the filtration based on reputable sources such as automotive history databases, brand websites, or Wikipedia. Please keep items separatelly if the company name was actual for some historycal period of time.\nIMPORTANT - Please response JSON array with processed marque names WITHOUT formatting (plain text).\n\nHere's the JSON array with marques from the DB:\n[\"JBA\",\"JC\",\"JC Sceriffa\",\"JCM\",\"JI Case\",\"JPR Cars\",\"JPS\",\"Jago\",\"Jaguar\",\"James\",\"Jameson\",\"Jannarelly\",\"Janßen\",\"Jato\",\"Javan Sports Cars\",\"Jawa\",\"Jawa Moto\",\"Jeep\",\"Jeepney\",\"Jeffery\",\"Jensen\",\"Jewett\",\"Jide\",\"Jim Turner\",\"Jimco\",\"John Deere\",\"John Deere-Lanz\",\"Johnson\",\"Jomi\",\"Jordan\",\"Jowett\",\"Junak\"]",
    "Hi ChatGPT. I'm working on the retro cars sales website. I have the vehicle marques list from my DB. Could you please do several things with it:\n- Exclude the duplicate marques (sometimes it's possible to have different namings of the same marques). Please confirm the filtration based on reputable sources such as automotive history databases, brand websites, or Wikipedia. Please keep items separatelly if the company name was actual for some historycal period of time.\nIMPORTANT - Please response JSON array with processed marque names WITHOUT formatting (plain text).\n\nHere's the JSON array with marques from the DB:\n[\"K-1\",\"KAMAZ\",\"KCC\",\"KTM\",\"KVA\",\"Kaelble\",\"Kaimann\",\"Kaiser\",\"Kaiser Jeep\",\"Kaiser-Frazer\",\"Kali\",\"Karkowsky\",\"Karma Automotive\",\"Kawasaki\",\"Keinath\",\"Kelkel\",\"Kellison\",\"Kellison Classic Cars\",\"Kelmark\",\"Kema\",\"Kenilworth\",\"Kenworth\",\"Kerry\",\"Kia\",\"Kieft\",\"Kiel\",\"King\",\"Kip\",\"Kirkham\",\"Kirowez\",\"Kissel\",\"Kleinschnittger\",\"Knaus\",\"Knox\",\"Koenigsegg\",\"Koenigsegg Automotive AB\",\"Kohlmus\",\"Kougar\",\"Kover\",\"Kovrovec\",\"KrAZ\",\"Kramer\",\"Krause\",\"Krauseco\",\"Krauser\",\"Kreidler\",\"Kreidler Van Veen\",\"Krieger\",\"Krümpel\",\"Kurtis\",\"Kurtis Kraft\",\"Kässbohrer Setra\",\"Kögel\",\"König\",\"Kühner & Berger\"]",
    "Hi ChatGPT. I'm working on the retro cars sales website. I have the vehicle marques list from my DB. Could you please do several things with it:\n- Exclude the duplicate marques (sometimes it's possible to have different namings of the same marques). Please confirm the filtration based on reputable sources such as automotive history databases, brand websites, or Wikipedia. Please keep items separatelly if the company name was actual for some historycal period of time.\nIMPORTANT - Please response JSON array with processed marque names WITHOUT formatting (plain text).\n\nHere's the JSON array with marques from the DB:\n[\"L. Burry and Cie.\",\"L.M.X.\",\"L.R. Roadsters\",\"LA Exotics\",\"LDV\",\"LHB\",\"LMC\",\"LML\",\"LTI\",\"La Buire\",\"La Licorne\",\"LaFayette\",\"LaSalle\",\"Lada\",\"Lafer\",\"Laffly\",\"Laforza\",\"Lagonda\",\"Lamborghini\",\"Lambretta\",\"Lanchester\",\"Lancia\",\"Land Rover\",\"Landini\",\"Lanz\",\"Laurin & Klement - Skoda\",\"Lavazza\",\"Laverda\",\"Lawil\",\"Le Patron\",\"Le Zèbre\",\"Lea-Francis\",\"Ledl\",\"Legnano\",\"Lely\",\"Lem\",\"Lenham\",\"Levante\",\"Levis\",\"Levis Motorcycles\",\"Lexus\",\"Leyland\",\"Leyland Authi\",\"Leyton House\",\"Light Car Company\",\"Ligier\",\"Lincoln\",\"Lindner\",\"Linke-Hofmann-Busch\",\"Lion-Peugeot\",\"Lister\",\"Listerbell\",\"Lito\",\"Lloyd\",\"Lloyd Motoren Werke\",\"Local Motors\",\"Locomobile\",\"Locust\",\"Lohner\",\"Lola\",\"Lola-Aston Martin\",\"Lomax\",\"Lombardi\",\"London Taxis International\",\"Longjia\",\"Lorinser\",\"Lorraine-Dietrich\",\"Lotus\",\"Louven\",\"Lozier\",\"LuAZ\",\"Lube\",\"Lucchini\",\"Lucid\",\"Lucra\",\"Lynx\",\"Léon Bollée\"]",
    "Hi ChatGPT. I'm working on the retro cars sales website. I have the vehicle marques list from my DB. Could you please do several things with it:\n- Exclude the duplicate marques (sometimes it's possible to have different namings of the same marques). Please confirm the filtration based on reputable sources such as automotive history databases, brand websites, or Wikipedia. Please keep items separatelly if the company name was actual for some historycal period of time.\nIMPORTANT - Please response JSON array with processed marque names WITHOUT formatting (plain text).\n\nHere's the JSON array with marques from the DB:\n[\"M.M.\",\"MAN\",\"MAN-VW\",\"MAS\",\"MAT\",\"MBK\",\"MDA\",\"MEV\",\"MEX\",\"MG\",\"MIAG\",\"MK\",\"MKP\",\"MNR\",\"MV Agusta\",\"MV Avello\",\"MVS\",\"MZ\",\"Maaco\",\"Mack\",\"Madgwick\",\"Magda\",\"Magirus-Deutz\",\"Magnat-Debon\",\"Magnate P708\",\"Magni\",\"Mahindra\",\"Maico\",\"Malaguti\",\"Malanca\",\"Malicet & Blin\",\"Manderbach\",\"Manet\",\"Mania\",\"Manta\",\"Marcadier\",\"March\",\"March Engineering\",\"March-BMW\",\"March-Cosworth\",\"Marcos\",\"Marendaz\",\"Marlin\",\"Marmon\",\"Marquette\",\"Mars\",\"Mars-Werke Nürnberg\",\"Marsh\",\"Martin\",\"Martin & Walker\",\"Maserati\",\"Massey-Ferguson\",\"Massey-Harris\",\"Matchless\",\"Matford\",\"Mathis\",\"Matra\",\"Matra-Simca\",\"Maxim\",\"Maxwell\",\"Maybach\",\"Mayr\",\"Mazda\",\"McBurnie\",\"McLaren\",\"McLaren Automotive\",\"McLaren-Elva\",\"McLaughlin\",\"McLaughlin-Buick\",\"Mega\",\"Meili\",\"Meister\",\"Melkus\",\"Mercedes\",\"Mercedes-AMG\",\"Mercedes-Benz\",\"Mercedes-Knight\",\"Mercer\",\"Mercury\",\"Merkel\",\"Merkur\",\"Merlin\",\"Merlyn\",\"Messerschmitt\",\"Messerschmitt / FMR\",\"Metaline\",\"Meteor\",\"Metz\",\"Mi-Val\",\"Microplas\",\"Midas\",\"Middlebridge\",\"Middlebridge Scimitar\",\"Midget Motors\",\"Miele\",\"Miersch\",\"Mignonette-Luap\",\"Mikafa\",\"Mikrus MR-300\",\"Milan\",\"Milani\",\"Milburn\",\"Milburn Electric\",\"Militaire\",\"Miller\",\"Miller Balsamo\",\"Miller PBS\",\"Minardi\",\"Minari\",\"Minerva\",\"Mini\",\"Minotto\",\"Miracle\",\"Mitchell\",\"Mitjet\",\"Mitsubishi\",\"Mitsubishi Motors\",\"Mitsuoka\",\"Miura\",\"Mochet\",\"Modena Designs\",\"Mohr\",\"Momo\",\"Monarch\",\"Mondial\",\"Monet-Goyon\",\"Monos\",\"Montesa\",\"Montesa - Honda\",\"Monteverdi\",\"Moretti\",\"Morgan\",\"Morgan Motor Company\",\"Morris\",\"Mors\",\"Moschella\",\"Moskvich\",\"Moskvitch\",\"Moskwitsch\",\"Mosler\",\"Moss\",\"Mostard\",\"Moto Ballant\",\"Moto CM\",\"Moto Galloni\",\"Moto Guzzi\",\"Moto Martin\",\"Moto Morini\",\"Moto Rumi\",\"Moto Rêve\",\"Moto Sachs\",\"Moto Tansini\",\"Moto Torpado\",\"Motobi\",\"Motoblog\",\"Motobécane\",\"Motoconfort\",\"Motom\",\"Motomec\",\"Motoped\",\"Motori Minarelli\",\"Motosacoche\",\"Motovespa\",\"Motron\",\"Mowag\",\"Moyer\",\"Mulag\",\"Multicar\",\"Muntz\",\"Murena\",\"Mustang\",\"Myers Motors\",\"Méray\",\"Münch\"]",
    "Hi ChatGPT. I'm working on the retro cars sales website. I have the vehicle marques list from my DB. Could you please do several things with it:\n- Exclude the duplicate marques (sometimes it's possible to have different namings of the same marques). Please confirm the filtration based on reputable sources such as automotive history databases, brand websites, or Wikipedia. Please keep items separatelly if the company name was actual for some historycal period of time.\nIMPORTANT - Please response JSON array with processed marque names WITHOUT formatting (plain text).\n\nHere's the JSON array with marques from the DB:\n[\"N.A.W.\",\"NCR\",\"NG\",\"NIO\",\"NSU\",\"NSU-Fiat\",\"NV\",\"Nagant\",\"Nagetusch\",\"Namco\",\"Napier\",\"Naples Sabot\",\"Nardi\",\"Nash\",\"Nash MC\",\"Nassetti\",\"National\",\"Navistar International\",\"Naylor\",\"Neander\",\"Neckar\",\"Negrini\",\"Nekaf\",\"Neracar\",\"Nerus\",\"Nestoria\",\"New Hudson\",\"New Imperial\",\"New Map\",\"Nike\",\"Nimbus\",\"Nissan\",\"Noble\",\"Nomad\",\"Nordtrak\",\"Norma\",\"Normag\",\"Normag-Zorge\",\"Norman\",\"Norsjö\",\"North Coast Custom\",\"Norton\",\"Norvin\",\"Nostalgia\",\"Nostalgic Edition\",\"Nota\",\"Notin\",\"Nubodi\",\"Nuffield\",\"Nuys\"]",
    "Hi ChatGPT. I'm working on the retro cars sales website. I have the vehicle marques list from my DB. Could you please do several things with it:\n- Exclude the duplicate marques (sometimes it's possible to have different namings of the same marques). Please confirm the filtration based on reputable sources such as automotive history databases, brand websites, or Wikipedia. Please keep items separatelly if the company name was actual for some historycal period of time.\nIMPORTANT - Please response JSON array with processed marque names WITHOUT formatting (plain text).\n\nHere's the JSON array with marques from the DB:\n[\"O.E.C.\",\"O.S.C.A.\",\"OCMA Devil\",\"OK Supreme\",\"OM\",\"OSCA\",\"OTAS\",\"OTO Melara\",\"Oakland\",\"Oakland Motor Car Company\",\"Officine Meccaniche\",\"Officine Stampaggi Industriali\",\"Ogle\",\"Oldsmobile\",\"Ollearo\",\"Olson\",\"Omega\",\"Omer\",\"Onyx\",\"Opel\",\"Oreca\",\"Orenstein & Koppel\",\"Orient\",\"Orsa\",\"Osa\",\"Osella\",\"Oshkosh\",\"Ossa\",\"Ostner\",\"Otten\",\"Overfinch\",\"Overland\",\"Owen\"]",
    "Hi ChatGPT. I'm working on the retro cars sales website. I have the vehicle marques list from my DB. Could you please do several things with it:\n- Exclude the duplicate marques (sometimes it's possible to have different namings of the same marques). Please confirm the filtration based on reputable sources such as automotive history databases, brand websites, or Wikipedia. Please keep items separatelly if the company name was actual for some historycal period of time.\nIMPORTANT - Please response JSON array with processed marque names WITHOUT formatting (plain text).\n\nHere's the JSON array with marques from the DB:\n[\"P&M\",\"PAMAG Paderborn\",\"PCS\",\"PD\",\"PG\",\"PGO\",\"PTV\",\"Packard\",\"Pagani\",\"Paige\",\"Paige-Detroit\",\"Palliser\",\"Paloma\",\"Pamax\",\"Panhard\",\"Panhard & Levassor\",\"Pannonia\",\"Panoz\",\"Panther\",\"Panther Motorcycles\",\"Panther Westwinds\",\"Pantherwerke AG\",\"Parilla\",\"Pasqualetti\",\"Pastiche\",\"Paterson\",\"Patriarca\",\"Paul Scott\",\"Paulussen\",\"Pavesi\",\"Peel\",\"Peerless\",\"Peerless (UK)\",\"Peerless (USA)\",\"Pegaso\",\"Pembleton\",\"Penske\",\"Penta\",\"Penton\",\"Perana\",\"Peraves\",\"Peripoli\",\"Peripoli Giulietta\",\"Perugina\",\"Peterbilt\",\"Petronas\",\"Peugeot\",\"Phebus\",\"Phillips\",\"Phoenix\",\"Phoenix-Cobra\",\"Phänomen\",\"Piaggio\",\"Piazza\",\"Piccard-Pictet\",\"Pierce-Arrow\",\"Piero Patria\",\"Pilbeam\",\"Pilgrim\",\"Pininfarina\",\"Piper\",\"Pirotta\",\"Plymouth\",\"Poirier\",\"Polaris\",\"Polestar\",\"Polski FIAT\",\"Polyphon-Musikwerke\",\"Poncin\",\"Pontiac\",\"Pope-Toledo\",\"Porsche\",\"Porsche-Diesel\",\"Posdam\",\"Powell\",\"Praga\",\"Pratt-Elkhart\",\"Prester\",\"Prevost\",\"Primus\",\"Progress\",\"Prost\",\"Proteus\",\"Puch\",\"Puch Frigerio\",\"Puli\",\"Pulse Litestar\",\"Puma\",\"Pur Sang\"]",
    "Hi ChatGPT. I'm working on the retro cars sales website. I have the vehicle marques list from my DB. Could you please do several things with it:\n- Exclude the duplicate marques (sometimes it's possible to have different namings of the same marques). Please confirm the filtration based on reputable sources such as automotive history databases, brand websites, or Wikipedia. Please keep items separatelly if the company name was actual for some historycal period of time.\nIMPORTANT - Please response JSON array with processed marque names WITHOUT formatting (plain text).\n\nHere's the JSON array with marques from the DB:\n[\"QEK\",\"Quadix\",\"Quantum\",\"Queen\",\"Qvale\"]",
    "Hi ChatGPT. I'm working on the retro cars sales website. I have the vehicle marques list from my DB. Could you please do several things with it:\n- Exclude the duplicate marques (sometimes it's possible to have different namings of the same marques). Please confirm the filtration based on reputable sources such as automotive history databases, brand websites, or Wikipedia. Please keep items separatelly if the company name was actual for some historycal period of time.\nIMPORTANT - Please response JSON array with processed marque names WITHOUT formatting (plain text).\n\nHere's the JSON array with marques from the DB:\n[\"RAM\",\"RCB\",\"RCH Replicar Hellas\",\"REO\",\"REX\",\"RGS Atalanta\",\"RMA\",\"RMW\",\"RUF\",\"RV\",\"Rabeneick\",\"Racing Green\",\"Radical\",\"Radior\",\"Railton\",\"Rainier\",\"Raleigh\",\"Rally\",\"Ralt\",\"Rambler\",\"Rambler-Renault\",\"Ranger\",\"Rapido\",\"Rastatt\",\"Rauch & Lang\",\"Ravat\",\"Raymond Mays\",\"Rayton Fissore\",\"Reading Standard\",\"Real-Rotax\",\"Realm\",\"Recreation\",\"Reform\",\"Regal\",\"Reimann\",\"Reliant\",\"Renault\",\"Rewaco\",\"Rex-Werke München\",\"Rexer\",\"Reynard\",\"Reynolds Boughton\",\"Rezvani\",\"Rhony’x\",\"Ricardo\",\"Rickenbacker\",\"Rickman\",\"Ridley\",\"Riedel Motoren AG\",\"Riley\",\"Riley & Scott\",\"Rimac\",\"Rinspeed\",\"Ritscher\",\"Riva\",\"Riverside\",\"Riverside Benelli\",\"Rivian\",\"Rixe\",\"Rizzato\",\"Roamer\",\"Roaring Forties\",\"Robin Hood\",\"Rochdale\",\"Rochet\",\"Rochet-Schneider\",\"Rockne\",\"Roger Stampers\",\"Rohmann\",\"Rokon\",\"Rolland-Pilain\",\"Rolls-Royce\",\"Rolux\",\"Romeo\",\"Rometsch\",\"Ronart\",\"Rondeau\",\"Rondel\",\"Rondine Copeta\",\"Roosevelt\",\"Roper\",\"Roselli Colli\",\"Rosengart\",\"Rossion Q1\",\"Rota\",\"Rovena\",\"Rover\",\"Rovin\",\"Royal Enfield\",\"Royale\",\"Rudge\",\"Rudge-Whitworth\",\"Rudolph\",\"Ruf Automobile\",\"Rugby\",\"Ruhrstahl\",\"Rumi\",\"Rupp\",\"Rush\",\"Ruska\",\"Ruxton\",\"Réne Bonnet\",\"Röhr\"]",
    "Hi ChatGPT. I'm working on the retro cars sales website. I have the vehicle marques list from my DB. Could you please do several things with it:\n- Exclude the duplicate marques (sometimes it's possible to have different namings of the same marques). Please confirm the filtration based on reputable sources such as automotive history databases, brand websites, or Wikipedia. Please keep items separatelly if the company name was actual for some historycal period of time.\nIMPORTANT - Please response JSON array with processed marque names WITHOUT formatting (plain text).\n\nHere's the JSON array with marques from the DB:\n[\"SAMA\",\"SCAT-Ceirano\",\"SEAT\",\"SECMA\",\"SFV\",\"SHL\",\"SIAMT\",\"SIFTT\",\"SIS Sachs\",\"SMV\",\"SMZ\",\"SPA\",\"SR\",\"SSC\",\"SSR-Motorsports\",\"SWM\",\"Saab\",\"Sabra\",\"Sachsenring\",\"Safir\",\"Saier\",\"Saker\",\"Saleen\",\"Salira\",\"Salmson\",\"Salsbury\",\"Samco\",\"Same\",\"Sammio\",\"Sanglas\",\"Santana\",\"Sanvenero\",\"Saporoshez\",\"Saroléa\",\"Sass\",\"Saturn\",\"Sauber\",\"Saurer\",\"Saviem\",\"Saxon\",\"Sbarro\",\"Scammell\",\"Scania\",\"Scania-Vabis\",\"Scarab\",\"Sceptre\",\"Schanzlin\",\"Scheib\",\"Schlepperwerk Nordhausen\",\"Schlüter\",\"Schmid\",\"Schollmeyer & Mahler\",\"Schweikert\",\"Schäfer\",\"Schüttoff AG\",\"Scion\",\"Scoiattolo\",\"Scomadi\",\"Scootacar\",\"Scott\",\"Scripps-Booth\",\"Seagrave\",\"Sebring\",\"Sebring-Vanguard\",\"Seeley\",\"Seibt\",\"Sendling\",\"Serenissima\",\"Sertum\",\"Serveta Lambretta\",\"Shadow\",\"Shamrock\",\"Shay\",\"Shelby\",\"Shelby American\",\"Sheldonhurst\",\"Sherco\",\"Sherpley\",\"Shirley\",\"Siata\",\"Siata-Ford\",\"Sicra\",\"Silk\",\"Silnes-Offenhauser Tomshe\",\"Sima-Violet\",\"Simca\",\"Simca Fiat\",\"Simonini\",\"Simplex\",\"Simplex Crane\",\"Simplex Manufacturing Corporation\",\"Simpson\",\"Simson\",\"Sin Cars\",\"Singer\",\"Siva\",\"Sizaire-Berwick\",\"Skoda\",\"Smart\",\"Snowberger Offenhauser\",\"Solex\",\"Solo\",\"Southern Roadcraft\",\"Sovam\",\"Soyer\",\"Spada\",\"Spania GTA Spano\",\"Sparta\",\"Spartan\",\"Spartan Cars\",\"Sparton\",\"Speedwell\",\"Spice\",\"Spirit\",\"Spitaler\",\"Spyker\",\"Squire\",\"Squire Car Manufacturing Company\",\"Ssangyong\",\"Standard\",\"Stanley\",\"Stanley Motor Carriage Company\",\"Star\",\"Steadman\",\"Stearns-Knight\",\"Steffey\",\"Steib\",\"Steinherr\",\"Steinwinter\",\"Sterckeman\",\"Sterling Autocycle\",\"Sterling Motor Cars\",\"Sterzi\",\"Stevens-Duryea\",\"Stewart & Stevenson\",\"Steyr\",\"Steyr-Daimler-Puch\",\"Steyr-Fiat\",\"Steyr-Opel\",\"Steyr-Puch\",\"Stihl\",\"Stock\",\"Stoewer\",\"Stola\",\"Straker-Squire\",\"Strohm\",\"Studebaker\",\"Stutz\",\"Styl'son\",\"Subaru\",\"Suecia\",\"Suffolk\",\"Sulzer\",\"Sunbeam\",\"Sunbeam Cycles\",\"Sunbeam-Talbot\",\"Suncar\",\"Super Aguri\",\"Superformance\",\"Superlite\",\"Surrey\",\"Surtees\",\"Suzuki\",\"Swallow\",\"Swallow Doretti\",\"Swift\",\"Sylva\",\"Symbol\",\"Sénéchal\"]",
    "Hi ChatGPT. I'm working on the retro cars sales website. I have the vehicle marques list from my DB. Could you please do several things with it:\n- Exclude the duplicate marques (sometimes it's possible to have different namings of the same marques). Please confirm the filtration based on reputable sources such as automotive history databases, brand websites, or Wikipedia. Please keep items separatelly if the company name was actual for some historycal period of time.\nIMPORTANT - Please response JSON array with processed marque names WITHOUT formatting (plain text).\n\nHere's the JSON array with marques from the DB:\n[\"T.E.C.\",\"TGM\",\"TM Racing\",\"TRK\",\"TVR\",\"TWS\",\"Tabbert\",\"Talbot\",\"Talbot-Lago\",\"Talbot-Matra\",\"Tanesini\",\"Tarpan\",\"Tatra\",\"Taurus\",\"Taylor-Dunn\",\"Teal\",\"Tecno\",\"Tecnomoto\",\"Teledyne Continental Cheetah\",\"Templar\",\"Tempo\",\"Terradyne\",\"Terraplane\",\"Terrot\",\"Tesla\",\"Tesserault\",\"Testi\",\"Tettner\",\"The Boeing Company\",\"The Detroit Electric\",\"The Famous James\",\"The H.H. Babcock Company\",\"The Henney Motor Company\",\"The Scott Motorcycle Company\",\"Thomann\",\"Thomas B. Jeffery Company\",\"Thomas Motor Company\",\"Thor\",\"Thornycroft\",\"Thoroughbred\",\"Thunder Ranch\",\"Thurner\",\"Tiga\",\"Timeless\",\"Titan\",\"ToJ\",\"Tofas\",\"Tojeiro\",\"Tojeiro-Climax\",\"Tomaszo\",\"Tomos\",\"Toreador\",\"Tornado\",\"Tornax\",\"Torpedo\",\"Touring Superleggera\",\"Toyota\",\"Trabant\",\"Trawo\",\"Treser\",\"TriBSA\",\"Tribute\",\"Trident\",\"Trigano\",\"Triking\",\"Triple C\",\"Triple E\",\"Tritan Ventures\",\"Triton\",\"Triumph\",\"Triumph (TWN)\",\"Triumph Motorcycles\",\"Trojan\",\"Tröller\",\"Tucker 48\",\"Tuk-Tuk\",\"Turismo\",\"Turner\",\"Turrinelli\",\"Twin Coach\",\"Tyrrell\"]",
    "Hi ChatGPT. I'm working on the retro cars sales website. I have the vehicle marques list from my DB. Could you please do several things with it:\n- Exclude the duplicate marques (sometimes it's possible to have different namings of the same marques). Please confirm the filtration based on reputable sources such as automotive history databases, brand websites, or Wikipedia. Please keep items separatelly if the company name was actual for some historycal period of time.\nIMPORTANT - Please response JSON array with processed marque names WITHOUT formatting (plain text).\n\nHere's the JSON array with marques from the DB:\n[\"UAZ\",\"UMM\",\"URS\",\"UT\",\"Ultima\",\"Unic\",\"Unipower\",\"Unique Autocraft\",\"Unitrak\",\"Universal\",\"Ural\",\"Ursus\",\"Urus\"]",
    "Hi ChatGPT. I'm working on the retro cars sales website. I have the vehicle marques list from my DB. Could you please do several things with it:\n- Exclude the duplicate marques (sometimes it's possible to have different namings of the same marques). Please confirm the filtration based on reputable sources such as automotive history databases, brand websites, or Wikipedia. Please keep items separatelly if the company name was actual for some historycal period of time.\nIMPORTANT - Please response JSON array with processed marque names WITHOUT formatting (plain text).\n\nHere's the JSON array with marques from the DB:\n[\"VEB Gartenbautechnik\",\"VELAM\",\"VM\",\"VOMAG\",\"VOR\",\"Valiant\",\"Van Diemen\",\"Van Grinsven\",\"Van Veen\",\"Vanclee\",\"Vanden Plas\",\"Vanderhall\",\"Vanguard\",\"Vanwall\",\"Vauxhall\",\"Vector\",\"Velocette\",\"Velorex\",\"Veloto\",\"Venom\",\"Venturi\",\"Veritas\",\"Verona\",\"Vespa\",\"Victor\",\"Victoria\",\"Victory\",\"Villa\",\"Villiers\",\"Vincent\",\"Vincent Motorcycles\",\"Vintage Speedsters\",\"Vixen\",\"Volkswagen\",\"Volpini\",\"Volugrafo\",\"Volvo\",\"Voxan\",\"Vulcan\",\"Vyatka\",\"Vyrus\",\"VéloSoleX\"]",
    "Hi ChatGPT. I'm working on the retro cars sales website. I have the vehicle marques list from my DB. Could you please do several things with it:\n- Exclude the duplicate marques (sometimes it's possible to have different namings of the same marques). Please confirm the filtration based on reputable sources such as automotive history databases, brand websites, or Wikipedia. Please keep items separatelly if the company name was actual for some historycal period of time.\nIMPORTANT - Please response JSON array with processed marque names WITHOUT formatting (plain text).\n\nHere's the JSON array with marques from the DB:\n[\"W.A.M.\",\"WASP Yahama\",\"WFM\",\"WK\",\"Wahl\",\"Wall\",\"Walz\",\"Wanderer\",\"Warchalowski\",\"Warszawa\",\"Wartburg\",\"Warwick\",\"WaterCar\",\"Watsonian\",\"Waverley\",\"Weferlinger Heimstolz\",\"Weineck\",\"Weippert\",\"Werner\",\"Wesseler\",\"Westcott Motor Car Company\",\"Western Flyer\",\"Westfalia\",\"Westfield\",\"Whippet\",\"White\",\"White Motor Company\",\"Whizzer\",\"Wiesmann\",\"Wilk\",\"Williams\",\"Williams & Pritchard\",\"Wills Sainte Claire\",\"Willys\",\"Willys-Knight\",\"Willys-Overland\",\"Willys-Viasa\",\"Wimmer\",\"Windhoff\",\"Wingfield\",\"Winnebago\",\"Winton\",\"Witte\",\"Wittek\",\"Wlost\",\"Wolf\",\"Wolf Racing Cars\",\"Wolfbart\",\"Wolga\",\"Wolseley\",\"Wolseley-Siddeley\",\"Würdig\"]",
    "Hi ChatGPT. I'm working on the retro cars sales website. I have the vehicle marques list from my DB. Could you please do several things with it:\n- Exclude the duplicate marques (sometimes it's possible to have different namings of the same marques). Please confirm the filtration based on reputable sources such as automotive history databases, brand websites, or Wikipedia. Please keep items separatelly if the company name was actual for some historycal period of time.\nIMPORTANT - Please response JSON array with processed marque names WITHOUT formatting (plain text).\n\nHere's the JSON array with marques from the DB:\n[\"XP\",\"XT3\"]",
    "Hi ChatGPT. I'm working on the retro cars sales website. I have the vehicle marques list from my DB. Could you please do several things with it:\n- Exclude the duplicate marques (sometimes it's possible to have different namings of the same marques). Please confirm the filtration based on reputable sources such as automotive history databases, brand websites, or Wikipedia. Please keep items separatelly if the company name was actual for some historycal period of time.\nIMPORTANT - Please response JSON array with processed marque names WITHOUT formatting (plain text).\n\nHere's the JSON array with marques from the DB:\n[\"Yamaha\",\"Yugo\"]",
    "Hi ChatGPT. I'm working on the retro cars sales website. I have the vehicle marques list from my DB. Could you please do several things with it:\n- Exclude the duplicate marques (sometimes it's possible to have different namings of the same marques). Please confirm the filtration based on reputable sources such as automotive history databases, brand websites, or Wikipedia. Please keep items separatelly if the company name was actual for some historycal period of time.\nIMPORTANT - Please response JSON array with processed marque names WITHOUT formatting (plain text).\n\nHere's the JSON array with marques from the DB:\n[\"Zagato\",\"Zakspeed\",\"Zastava\",\"Zato\",\"Zedel\",\"Zenith\",\"Zenos\",\"Zerchot\",\"Zero Engineering\",\"Zetor\",\"Zettelmeyer\",\"Zhong Shen\",\"ZiL\",\"Zichner\",\"Ziegler\",\"Zimmer\",\"Zundapp\",\"Zytek\",\"Zündapp\"]",
    "Hi ChatGPT. I'm working on the retro cars sales website. I have the vehicle marques list from my DB. Could you please do several things with it:\n- Exclude the duplicate marques (sometimes it's possible to have different namings of the same marques). Please confirm the filtration based on reputable sources such as automotive history databases, brand websites, or Wikipedia. Please keep items separatelly if the company name was actual for some historycal period of time.\nIMPORTANT - Please response JSON array with processed marque names WITHOUT formatting (plain text).\n\nHere's the JSON array with marques from the DB:\n[\"Česká Zbrojovka Strakonice (CZ)\",\"Čezeta\"]",
    "Hi ChatGPT. I'm working on the retro cars sales website. I have the vehicle marques list from my DB. Could you please do several things with it:\n- Exclude the duplicate marques (sometimes it's possible to have different namings of the same marques). Please confirm the filtration based on reputable sources such as automotive history databases, brand websites, or Wikipedia. Please keep items separatelly if the company name was actual for some historycal period of time.\nIMPORTANT - Please response JSON array with processed marque names WITHOUT formatting (plain text).\n\nHere's the JSON array with marques from the DB:\n[\"ɛ̃fini\"]"
];


export const marqueList = [
    "A.J.S.",
    "A.P.C. Motor Company",
    "ABC",
    "AC",
    "ACM",
    "ADM",
    "AEC",
    "AFM",
    "AHS",
    "AJS Motorcycles",
    "AK",
    "ALCA",
    "ALPINA",
    "AM General",
    "AMC",
    "AME",
    "AMF Harley-Davidson",
    "AMS",
    "ARO",
    "ASA",
    "ASM",
    "ATK",
    "ATS",
    "AWO (Simson)",
    "AWS",
    "AWZ",
    "Abarth",
    "Abarth-Simca",
    "Ace",
    "Ache Frères",
    "Achilles",
    "Acoma",
    "Acura",
    "Adams",
    "Adler",
    "Adly",
    "Adria",
    "Aeon-Motor",
    "Aermacchi",
    "Aermacchi Harley-Davidson",
    "Aero",
    "Aero Caproni",
    "Agrati",
    "Agrati-Garelli",
    "Ahrens-Fox",
    "Aiglon",
    "Airstream",
    "Aktiv Fisher",
    "Alba",
    "Albany",
    "Albar",
    "Albion",
    "Alco",
    "Alcyon",
    "Alfa Romeo",
    "Allard",
    "Allis Chalmers",
    "Allison",
    "Allstate",
    "Alma",
    "Alpenland",
    "Alpine",
    "Alpino",
    "Alta",
    "Alvis",
    "American Austin",
    "American Bantam",
    "American IronHorse",
    "American LaFrance",
    "American Motor Car Company",
    "Americar",
    "Amerio",
    "Amilcar",
    "Amphicar",
    "Amphicruiser",
    "Ancillotti",
    "Ancora",
    "Anglia Cars",
    "Ansaldo",
    "Antem",
    "Apal",
    "Apollo",
    "Aprilia",
    "Aquila",
    "Arab",
    "Arden",
    "Ardie",
    "Argo",
    "Ariel",
    "Ariel Motor Company",
    "Ariel Motorcycles",
    "Aristocat",
    "Ariès",
    "Arkley",
    "Arlen Ness",
    "Armstrong",
    "Armstrong Siddeley",
    "Arnolt",
    "Arnolt-Bristol",
    "Arnolt-MG",
    "Arrows",
    "Artega",
    "Ascar",
    "Ashley Laminates",
    "Asia",
    "Aspes",
    "Aston Martin",
    "Atala",
    "Atalanta",
    "Atterbury",
    "Auburn",
    "Audi",
    "Austermann",
    "Austin",
    "Austin Motor Company",
    "Austin-Healey",
    "Austro-Daimler",
    "Austro-Tatra",
    "Autech",
    "Auto Union",
    "Autobianchi",
    "Autocar",
    "Autokraft",
    "Automobiles Charron, Girardot et Voigt (CGV)",
    "Automobiles Julien",
    "Automobiles Talbot",
    "Automoto",
    "Autovia",
    "Autozam",
    "Avante",
    "Avanti",
    "Avton",
    "Avion",
    "Avions Voisin",
    "Avon",
    "Aztec",
    "B. F. Meyers & Company",
    "B.N.C.",
    "B.W.A.",
    "BAC",
    "BAC Mono",
    "BAE",
    "BAW",
    "BFG",
    "BIOD",
    "BJR",
    "BM",
    "BMA",
    "BMW",
    "BRA",
    "BRM",
    "BSA",
    "BSW",
    "Babiole",
    "Bacchelli e Villa",
    "Backdraft",
    "Badel",
    "Bailey",
    "Baillou",
    "Bajaj",
    "Baker Electric",
    "Balkan",
    "Ballot",
    "Bandini",
    "Banham",
    "Banjo",
    "Barkas",
    "Baron",
    "Bastei",
    "Bastert",
    "Batavus",
    "Bauer",
    "Baum",
    "Bautz",
    "Bayliss-Thomas",
    "Bean",
    "Beardmore Precision",
    "Beauford",
    "Beck",
    "Bedford",
    "Behnke",
    "Beijing Automobile Works",
    "Beilharz",
    "Belarus",
    "Belsize",
    "Benelli",
    "Benetton",
    "Benjamin",
    "Benova",
    "Bentley",
    "Benz",
    "Benz & Cie.",
    "Berger",
    "Berkeley",
    "Berliet",
    "Berna",
    "Bernardet",
    "Berneg",
    "Bertone",
    "Beta",
    "Bianchi",
    "Bianco",
    "Bieber",
    "Bimota",
    "Birkin",
    "Bischoff",
    "Biscúter",
    "Bismarck",
    "Bitter",
    "Bizzarrini",
    "Blue Bird",
    "Bobsy",
    "Bohse",
    "Boldmen",
    "Bolinder-Munktell",
    "Bombardier",
    "Bonanza",
    "Bond",
    "Boom",
    "Borghi",
    "Borgward",
    "Borgward-Iso",
    "Bosato Automobili Torino",
    "Boss Hoss",
    "Bourgeois",
    "Bourget",
    "Boursaud",
    "Bowler",
    "Bowler Motors",
    "Bown",
    "Boyer & Cie.",
    "Brabham",
    "Brabus",
    "Bradbury Motor Cycles",
    "Bradley",
    "Brasier",
    "Brasinca",
    "Bremen Sport Equipment",
    "Brennabor",
    "Brewster",
    "Bricklin",
    "Bridgestone Motorcycles",
    "Briggs Cunningham",
    "Brightwheel",
    "Brissonnet",
    "Bristol",
    "British Leyland",
    "Briton",
    "Brixton",
    "Broadspeed",
    "Brockhouse",
    "Brooke",
    "Brough Superior",
    "Brunton",
    "Bruseghini",
    "Brändle",
    "Bucci",
    "Bucciali",
    "Bucher",
    "Buckler",
    "Buell",
    "Bufori",
    "Bugatti",
    "Bugnotti",
    "Buick",
    "Bultaco",
    "Bungartz",
    "Burlington",
    "Burton",
    "Byers",
    "Böhmerland",
    "Böhringer",
    "Bücker",
    "Bührer",
    "Bürstner",
    "Büssing",
    "C.G.V.",
    "CAP",
    "CAV",
    "CCC",
    "CCM",
    "CDL",
    "CERA",
    "CG",
    "CMC",
    "CMP",
    "CN",
    "CR&S",
    "CZ",
    "Cadillac",
    "Cagiva",
    "Caldwell",
    "California Custom Coach",
    "Calthorpe",
    "Cameron",
    "Campagna Motors",
    "Can-Am",
    "Canada Cycle & Motor Company",
    "Cannondale Motorcycles",
    "Capriolo",
    "Caproni-Vizzola",
    "Carabela",
    "Caravelair",
    "Carbodies",
    "Carlsson",
    "Carniel",
    "Carrozzeria Castagna",
    "Carrozzeria Sports Cars",
    "Cartercar",
    "Carver",
    "Casal",
    "Casalini",
    "Case-IH",
    "Castiglioni",
    "Caterham",
    "Ceccato",
    "Ceirano",
    "Cemec",
    "Century Boat Company",
    "Cessna Aircraft Company",
    "Chadwick",
    "Chalmers Motor Company",
    "Chalmers-Detroit",
    "Chamonix NG Cars",
    "Champion",
    "Chandler",
    "Chang Jiang",
    "Charron",
    "Chateau",
    "Chater-Lea",
    "Checker",
    "Cheetah",
    "Chenard - Walcker",
    "Cheney-Triumph",
    "Chesil",
    "Chevrolet",
    "Chevron",
    "Chinook",
    "Chollet",
    "Chris-Craft",
    "Chrysler",
    "Chrysler-Simca",
    "Cimatti",
    "Cisitalia",
    "Citroën",
    "Citroën-Kegresse",
    "Cizeta",
    "Cizeta V16T",
    "Clark Cortez Motorhomes",
    "Classic Motor Carriages",
    "Classic Roadsters",
    "Classic Speed",
    "Clenet",
    "Cleveland",
    "Clyno",
    "Clément Panhard",
    "Clénet",
    "Coachmen",
    "Cobretti",
    "Cockshutt",
    "Colani",
    "Cole Motor Car Company",
    "Columbia",
    "Commer",
    "Compagnie Nationale Excelsior",
    "Condor",
    "Condor BMW",
    "Confederate",
    "Connaught",
    "Constructam",
    "Contemporary Classics",
    "Continent",
    "Cooper",
    "Cooper Car Company",
    "Cord",
    "Corona Brandenburg",
    "Corsar",
    "Corsini",
    "Costin Nathan",
    "Cottereau",
    "Cotton",
    "Courage",
    "Coussement",
    "Coventry Eagle",
    "Coventry-Eagle",
    "Covin",
    "Crane-Simplex",
    "Crawford-Ferrari",
    "Cretors",
    "Croco",
    "Crofton",
    "Croizemarie",
    "Crosley",
    "Crossley",
    "Crosslé",
    "Culebra",
    "Cunningham",
    "Cushman",
    "Cyklon",
    "Cyrus",
    "D-Rad",
    "DAF",
    "DB (Deutsch-Bonnet)",
    "DINA",
    "DKW",
    "DMW",
    "DOT",
    "Datsun",
    "Dauer",
    "David Brown",
    "Davies",
    "Davis",
    "Davrian",
    "Dax",
    "Day-Elder",
    "De Cadenet-Lola",
    "De Dion-Bouton",
    "De La Chapelle",
    "De Reu",
    "De Sanctis",
    "De Tomaso",
    "DeLorean",
    "DeSoto",
    "Delage",
    "Delahaye",
    "Delaunay-Belleville",
    "Dellow",
    "Delta Motors",
    "Demm",
    "Dennis",
    "Derbi",
    "Derby",
    "Derichs",
    "Deserter",
    "Deutz",
    "Devaux",
    "Devin",
    "Di Blasi",
    "Diamond T",
    "Diatto",
    "Diavolino",
    "Digue",
    "Diva",
    "Divco",
    "Dixi",
    "Dnepr",
    "Dodge",
    "Dollar",
    "Donkervoort",
    "Donnet-Zedel",
    "Dort",
    "Douglas",
    "Dover",
    "Dresch",
    "Dual-Ghia",
    "Ducati",
    "Duesenberg",
    "Dune Buggies",
    "Dunham",
    "Dunsmore",
    "Dutton",
    "Dürkopp-Werke",
    "E-M-F",
    "EBM",
    "EJS",
    "EMF",
    "EMW",
    "ERA",
    "ERF",
    "ESO",
    "ETV",
    "EWB Cars",
    "Eagle",
    "Ebro",
    "Ecarrus",
    "Eccles",
    "Eckert-Honda",
    "Edge",
    "Edsel",
    "Edwards",
    "Effeffe",
    "Egli",
    "Egli-Ducati",
    "Egli-Honda",
    "Egli-Kawasaki",
    "Egli-Suzuki",
    "Egli-Vincent",
    "Eicher",
    "Eicker",
    "Eifelland",
    "Eilers",
    "Elan",
    "Elcar",
    "Elddis Autoking",
    "Elden",
    "Elite",
    "Elva",
    "Empolini",
    "Emva",
    "Enfield-Allday",
    "English Mechanic",
    "Ensign",
    "Ensinger",
    "Envemo",
    "Enzmann",
    "Epperly",
    "Eriba",
    "Ermini",
    "Ermolli",
    "Ernst-Werke",
    "Erskine",
    "Es-Ka",
    "Escargot",
    "Essex",
    "Esterel",
    "Eunos",
    "Eura Caravan",
    "EuroBrun",
    "Evans",
    "Evanta",
    "Evante",
    "Everett-Morrison",
    "Ewing",
    "Excalibur",
    "Excelsior",
    "Excelsior Motor Company",
    "Excelsior-Henderson",
    "Express Werke",
    "F&S",
    "F.I.M.A.",
    "FAMO",
    "FASA-Renault",
    "FAUN",
    "FBW",
    "FFR",
    "FMR TG500",
    "FN",
    "FSC Zuk",
    "FSM",
    "FV Frangivento",
    "Facel Vega",
    "Factory Five",
    "Factory Five Racing",
    "Fafnir",
    "Fahr",
    "Fairthorpe",
    "Faka",
    "Falcon",
    "Falcon Shells",
    "Fantic",
    "Faranda",
    "Farbio",
    "Fargo",
    "Farmall",
    "Favor",
    "Favorit",
    "Federal",
    "Federal Motor Truck Company",
    "Felber",
    "Fendt",
    "Ferguson",
    "Feriela",
    "Ferrari",
    "Ferrario",
    "Ferves",
    "Fiat",
    "Fiatagri",
    "Fiberfab",
    "Fibral",
    "Fichtel & Sachs",
    "Fina Sport",
    "Fiorano",
    "Fischer Kawasaki",
    "Fisher",
    "Fisker",
    "Fittipaldi",
    "Flanders",
    "Fleetwood",
    "Fletcher",
    "Fleur de Lys",
    "Flint",
    "Flottweg",
    "Flxible",
    "Flying Merkel",
    "Focus",
    "Foden",
    "Ford",
    "Fordson",
    "Foreman",
    "Formosa",
    "Formula 27",
    "Fram-King",
    "Framo",
    "Francis Barnett",
    "Francis-Barnett",
    "Franklin",
    "Fratelli Ferrari",
    "Frazer Nash",
    "Freightliner",
    "Frera",
    "Frischauf",
    "Frisky",
    "Fuchs",
    "Fuji",
    "Fuldamobil",
    "Furore",
    "GAZ",
    "GBS",
    "GFG",
    "GMC",
    "GMG",
    "GN",
    "GP",
    "GRD",
    "GTA",
    "GTD",
    "GTM",
    "Gallina",
    "Ganna",
    "Garanzini",
    "Gardner",
    "Gardner Douglas",
    "Garelli",
    "Garia",
    "GasGas",
    "Gasmobile",
    "Gasser",
    "Gatsby",
    "Gatso",
    "Geier-Werke",
    "Gemballa",
    "Gentry",
    "Geo",
    "Georges Irat",
    "Gerosa",
    "Geser",
    "Ghezzi & Brian",
    "Ghia",
    "Ghostrider Choppers",
    "Giannini",
    "Giaur",
    "Gibbs",
    "Gilbern",
    "Gilco",
    "Gilera",
    "Gillet-Herstal",
    "Gillig",
    "Ginetta",
    "Gitan",
    "Gitane Test",
    "Giulietta",
    "Gladiator",
    "Gladstone",
    "Glas",
    "Glasspar",
    "Gnome et Rhône",
    "Goggomobil",
    "Goliath",
    "Gordini",
    "Gordon-Keeble",
    "Gorgus",
    "Gori",
    "Graham",
    "Graham-Paige",
    "Grandin",
    "Gray-Dort",
    "Grayson",
    "Grecav",
    "Greeves",
    "Griffith",
    "Griffon",
    "Grindlay Peerless",
    "Grinnall",
    "Grisham",
    "Gritzner",
    "Grumman Olson",
    "Gräf & Stift",
    "Grümer",
    "Guazzoni",
    "Gugel",
    "Gulf",
    "Gullwing",
    "Gumpert",
    "Gurgel",
    "Gutbrod",
    "Gwynne",
    "Göricke",
    "Güldner",
    "HAZ",
    "HE",
    "HELA",
    "HEOS",
    "HKT",
    "HMC",
    "HMO",
    "HMW",
    "HRD",
    "HRG",
    "HTS",
    "HWM",
    "Hadi",
    "Hagedorn",
    "Hahn",
    "Hanomag",
    "Hanomag-Henschel",
    "Hansa",
    "Harlette-Géco",
    "Harley-Davidson",
    "Harlé",
    "Harris-Léon Laisne",
    "Hartge",
    "Hatz",
    "Hawk",
    "Hayden",
    "Haynes",
    "Hazlewood",
    "Healey",
    "Healy",
    "Healy Designs",
    "Hecker",
    "Heidemann",
    "Heine-Velox",
    "Heinkel",
    "Hema",
    "Henderson",
    "Henderson Motorcycle",
    "Henley",
    "Hennessey Performance Engineering",
    "Henney",
    "Henschel",
    "Hercules",
    "Heritage",
    "Heron",
    "Hesketh",
    "Hesketh Motorcycles",
    "Heuliez",
    "Heynsdyk",
    "HiTec",
    "Hiawatha",
    "Hildebrand & Wolfmüller",
    "Hillman",
    "Hillmann",
    "Hindustan",
    "Hino",
    "Hirth",
    "Hispano-Alemán",
    "Hispano-Suiza",
    "Hobart",
    "Hobby",
    "Hodaka",
    "Hoffmann",
    "Holden",
    "Holder",
    "Holman-Moody",
    "Holsman",
    "Hommell",
    "Honda",
    "Hoppe",
    "Horch",
    "Horex",
    "Hosek",
    "Hot Car",
    "Hotchkiss",
    "Hotzenblitz",
    "Hudson",
    "Humber",
    "Humber Limited",
    "Hummel",
    "Hummer",
    "Hupmobile",
    "Huron",
    "Hurtan",
    "Husqvarna",
    "Hustler",
    "Hyde",
    "Hyundai",
    "Hägglunds",
    "Hénon",
    "Hürlimann",
    "I.S.S.I.",
    "IAME",
    "IFA",
    "IHC",
    "IKA",
    "ILO",
    "IMA",
    "IMC",
    "IMV",
    "IMZ-Ural",
    "INEOS",
    "IWL",
    "IZH",
    "Iconic Autobody",
    "Imperia",
    "Imperial",
    "Impéria Automobiles",
    "Inbrav",
    "Indian",
    "Indian Motorcycle",
    "Ineos Automotive",
    "Infiniti",
    "Innocenti",
    "Inter-State",
    "Intercamp",
    "Interclassic",
    "Intermeccanica",
    "International Harvester",
    "Intramotor Gloria",
    "Invicta",
    "Irmscher",
    "Isdera",
    "Iso",
    "Iso Rivolta",
    "Isotta Fraschini",
    "Isuzu",
    "Itala",
    "Italcaravan",
    "Italdesign Giugiaro",
    "Italjet",
    "Itasca",
    "Itom",
    "Iveco",
    "Iveco Magirus",
    "Ixion",
    "JBA",
    "JC",
    "JCM",
    "JI Case",
    "JPR Cars",
    "JPS",
    "Jago",
    "Jaguar",
    "James",
    "Jameson",
    "Jannarelly",
    "Janßen",
    "Jato",
    "Javan Sports Cars",
    "Jawa",
    "Jawa Moto",
    "Jeep",
    "Jeepney",
    "Jeffery",
    "Jensen",
    "Jewett",
    "Jide",
    "Jim Turner",
    "Jimco",
    "John Deere",
    "John Deere-Lanz",
    "Johnson",
    "Jomi",
    "Jordan",
    "Jowett",
    "Junak",
    "K-1",
    "KAMAZ",
    "KCC",
    "KTM",
    "KVA",
    "Kaelble",
    "Kaimann",
    "Kaiser",
    "Kaiser Jeep",
    "Kaiser-Frazer",
    "Kali",
    "Karkowsky",
    "Karma Automotive",
    "Kawasaki",
    "Keinath",
    "Kelkel",
    "Kellison",
    "Kellison Classic Cars",
    "Kelmark",
    "Kema",
    "Kenilworth",
    "Kenworth",
    "Kerry",
    "Kia",
    "Kieft",
    "Kiel",
    "King",
    "Kip",
    "Kirkham",
    "Kirowez",
    "Kissel",
    "Kleinschnittger",
    "Knaus",
    "Knox",
    "Koenigsegg",
    "Kohlmus",
    "Kougar",
    "Kover",
    "Kovrovec",
    "KrAZ",
    "Kramer",
    "Krause",
    "Krauseco",
    "Krauser",
    "Kreidler",
    "Kreidler Van Veen",
    "Krieger",
    "Krümpel",
    "Kurtis",
    "Kurtis Kraft",
    "Kässbohrer Setra",
    "Kögel",
    "König",
    "Kühner & Berger",
    "L. Burry and Cie.",
    "L.M.X.",
    "L.R. Roadsters",
    "LA Exotics",
    "LDV",
    "LHB",
    "LMC",
    "LML",
    "LTI",
    "La Buire",
    "La Licorne",
    "LaFayette",
    "LaSalle",
    "Lada",
    "Lafer",
    "Laffly",
    "Laforza",
    "Lagonda",
    "Lamborghini",
    "Lambretta",
    "Lanchester",
    "Lancia",
    "Land Rover",
    "Landini",
    "Lanz",
    "Laurin & Klement - Skoda",
    "Lavazza",
    "Laverda",
    "Lawil",
    "Le Patron",
    "Le Zèbre",
    "Lea-Francis",
    "Ledl",
    "Legnano",
    "Lely",
    "Lem",
    "Lenham",
    "Levante",
    "Levis",
    "Lexus",
    "Leyland",
    "Leyland Authi",
    "Leyton House",
    "Light Car Company",
    "Ligier",
    "Lincoln",
    "Lindner",
    "Linke-Hofmann-Busch",
    "Lion-Peugeot",
    "Lister",
    "Listerbell",
    "Lito",
    "Lloyd",
    "Lloyd Motoren Werke",
    "Local Motors",
    "Locomobile",
    "Locust",
    "Lohner",
    "Lola",
    "Lola-Aston Martin",
    "Lomax",
    "Lombardi",
    "London Taxis International",
    "Longjia",
    "Lorinser",
    "Lorraine-Dietrich",
    "Lotus",
    "Louven",
    "Lozier",
    "LuAZ",
    "Lube",
    "Lucchini",
    "Lucid",
    "Lucra",
    "Lynx",
    "Léon Bollée",
    "M.M.",
    "MAN",
    "MAN-VW",
    "Mazda",
    "MAS",
    "MAT",
    "MBK",
    "MDA",
    "MEV",
    "MEX",
    "MG",
    "MIAG",
    "MK",
    "MKP",
    "MNR",
    "MV Agusta",
    "MZ",
    "Maaco",
    "Mack",
    "Madgwick",
    "Magirus-Deutz",
    "Magnat-Debon",
    "Mahindra",
    "Maico",
    "Malaguti",
    "Malanca",
    "Malicet & Blin",
    "Manderbach",
    "Manet",
    "Mania",
    "Manta",
    "Marcadier",
    "March",
    "Marcos",
    "Marendaz",
    "Marlin",
    "Marmon",
    "Marquette",
    "Mars",
    "Messerschmitt",
    "Metaline",
    "Metz",
    "Microplas",
    "Midas",
    "Middlebridge",
    "Midget Motors",
    "Miele",
    "Mikafa",
    "Mikrus MR-300",
    "Milburn",
    "Milburn Electric",
    "Militaire",
    "Miller",
    "Minardi",
    "Minerva",
    "Mini",
    "Miracle",
    "Mitchell",
    "Mitsubishi",
    "Mitsuoka",
    "Modena Designs",
    "Monarch",
    "Monet-Goyon",
    "Montesa",
    "Monteverdi",
    "Morgan",
    "Morris",
    "Moskvich",
    "Mosler",
    "Mostard",
    "Moto Guzzi",
    "Moto Morini",
    "Motosacoche",
    "Motovespa",
    "Motron",
    "Mowag",
    "Mustang",
    "Myers Motors",
    "Méray",
    "Münch",
    "Mercedes",
    "Mercedes-AMG",
    "Mercedes-Benz",
    "Mercer",
    "Mercury",
    "Merkel",
    "Merkur",
    "Merlin",
    "Merlyn",
    "McLaren",
    "McLaren Automotive",
    "McLaren-Elva",
    "McLaughlin",
    "McLaughlin-Buick",
    "Matford",
    "Mathis",
    "Matra",
    "Matra-Simca",
    "Maxim",
    "Maxwell",
    "Maybach",
    "Mayr",
    "Melkus",
    "Motobécane",
    "Motoconfort",
    "Motom",
    "Motomec",
    "Motoped",
    "Motobi",
    "Madgwick",
    "Miller Balsamo",
    "Miller PBS",
    "March Engineering",
    "March-BMW",
    "March-Cosworth",
    "N.A.W.",
    "NCR",
    "NG",
    "NIO",
    "NSU",
    "NSU-Fiat",
    "Nagant",
    "Nagetusch",
    "Namco",
    "Napier",
    "Nardi",
    "Nash",
    "National",
    "Navistar International",
    "Naylor",
    "Neander",
    "Neckar",
    "Negrini",
    "Nekaf",
    "Neracar",
    "Nerus",
    "Nestoria",
    "New Hudson",
    "New Imperial",
    "Nike",
    "Nimbus",
    "Nissan",
    "Noble",
    "Nomad",
    "Nordtrak",
    "Norma",
    "Normag",
    "Norman",
    "Norsjö",
    "North Coast Custom",
    "Norton",
    "Norvin",
    "Nostalgia",
    "Nota",
    "Notin",
    "Nubodi",
    "Nuffield",
    "Nuys",
    "O.E.C.",
    "O.S.C.A.",
    "OCMA Devil",
    "OK Supreme",
    "OM",
    "OSCA",
    "OTAS",
    "OTO Melara",
    "Oakland",
    "Officine Meccaniche",
    "Officine Stampaggi Industriali",
    "Ogle",
    "Oldsmobile",
    "Ollearo",
    "Olson",
    "Omega",
    "Omer",
    "Onyx",
    "Opel",
    "Oreca",
    "Orenstein & Koppel",
    "Orient",
    "Orsa",
    "Osa",
    "Osella",
    "Oshkosh",
    "Ossa",
    "Ostner",
    "Otten",
    "Overfinch",
    "Overland",
    "Owen",
    "P&M",
    "PAMAG Paderborn",
    "PCS",
    "PD",
    "PG",
    "PGO",
    "PTV",
    "Packard",
    "Pagani",
    "Paige",
    "Palliser",
    "Paloma",
    "Pamax",
    "Panhard",
    "Panhard & Levassor",
    "Pannonia",
    "Panoz",
    "Panther",
    "Panther Motorcycles",
    "Panther Westwinds",
    "Parilla",
    "Pasqualetti",
    "Pastiche",
    "Paterson",
    "Patriarca",
    "Paul Scott",
    "Paulussen",
    "Pavesi",
    "Peel",
    "Peerless",
    "Pegaso",
    "Pembleton",
    "Penske",
    "Penta",
    "Penton",
    "Perana",
    "Peraves",
    "Peripoli",
    "Perugina",
    "Peterbilt",
    "Petronas",
    "Peugeot",
    "Phebus",
    "Phillips",
    "Phoenix",
    "Phänomen",
    "Piaggio",
    "Piazza",
    "Piccard-Pictet",
    "Pierce-Arrow",
    "Piero Patria",
    "Pilbeam",
    "Pilgrim",
    "Pininfarina",
    "Piper",
    "Pirotta",
    "Plymouth",
    "Poirier",
    "Polaris",
    "Polestar",
    "Polski FIAT",
    "Poncin",
    "Pontiac",
    "Pope-Toledo",
    "Porsche",
    "Porsche-Diesel",
    "Powell",
    "Praga",
    "Pratt-Elkhart",
    "Prester",
    "Prevost",
    "Primus",
    "Progress",
    "Prost",
    "Proteus",
    "Puch",
    "Puch Frigerio",
    "Puli",
    "Pulse Litestar",
    "Puma",
    "Pur Sang",
    "QEK",
    "Quadix",
    "Quantum",
    "Queen",
    "Qvale",
    "RAM",
    "RCB",
    "RCH Replicar Hellas",
    "REO",
    "REX",
    "RGS Atalanta",
    "RMA",
    "RMW",
    "RUF",
    "Rabeneick",
    "Racing Green",
    "Radical",
    "Radior",
    "Railton",
    "Rainier",
    "Raleigh",
    "Rally",
    "Ralt",
    "Rambler",
    "Rambler-Renault",
    "Ranger",
    "Rapido",
    "Rastatt",
    "Rauch & Lang",
    "Ravat",
    "Raymond Mays",
    "Rayton Fissore",
    "Reading Standard",
    "Real-Rotax",
    "Realm",
    "Recreation",
    "Reform",
    "Regal",
    "Reimann",
    "Reliant",
    "Renault",
    "Rewaco",
    "Rex-Werke München",
    "Reynard",
    "Reynolds Boughton",
    "Rezvani",
    "Rhony’x",
    "Ricardo",
    "Rickenbacker",
    "Rickman",
    "Ridley",
    "Riedel Motoren AG",
    "Riley",
    "Riley & Scott",
    "Rimac",
    "Rinspeed",
    "Ritscher",
    "Riva",
    "Riverside",
    "Riverside Benelli",
    "Rivian",
    "Rixe",
    "Rizzato",
    "Roamer",
    "Roaring Forties",
    "Robin Hood",
    "Rochdale",
    "Rochet",
    "Rochet-Schneider",
    "Rockne",
    "Roger Stampers",
    "Rohmann",
    "Rokon",
    "Rolland-Pilain",
    "Rolls-Royce",
    "Rolux",
    "Romeo",
    "Rometsch",
    "Ronart",
    "Rondeau",
    "Rondel",
    "Rondine Copeta",
    "Roosevelt",
    "Roper",
    "Roselli Colli",
    "Rosengart",
    "Rossion Q1",
    "Rota",
    "Rovena",
    "Rover",
    "Rovin",
    "Royal Enfield",
    "Royale",
    "Rudge",
    "Rudge-Whitworth",
    "Rudolph",
    "Ruf Automobile",
    "Rugby",
    "Ruhrstahl",
    "Rumi",
    "Rupp",
    "Rush",
    "Ruska",
    "Ruxton",
    "Réne Bonnet",
    "Röhr",
    "SAMA",
    "SCAT-Ceirano",
    "SEAT",
    "SECMA",
    "SFV",
    "SHL",
    "SIAMT",
    "SIFTT",
    "SIS Sachs",
    "SMV",
    "SMZ",
    "SPA",
    "SR",
    "SSC",
    "SSR-Motorsports",
    "SWM",
    "Saab",
    "Sabra",
    "Sachsenring",
    "Safir",
    "Saier",
    "Saker",
    "Saleen",
    "Salira",
    "Salmson",
    "Salsbury",
    "Samco",
    "Same",
    "Sammio",
    "Sanglas",
    "Santana",
    "Sanvenero",
    "Saporoshez",
    "Saroléa",
    "Sass",
    "Saturn",
    "Sauber",
    "Saurer",
    "Saviem",
    "Saxon",
    "Sbarro",
    "Scammell",
    "Scania",
    "Scania-Vabis",
    "Scarab",
    "Sceptre",
    "Schanzlin",
    "Scheib",
    "Schlepperwerk Nordhausen",
    "Schlüter",
    "Schmid",
    "Schollmeyer & Mahler",
    "Schweikert",
    "Schäfer",
    "Schüttoff AG",
    "Scion",
    "Scoiattolo",
    "Scomadi",
    "Scootacar",
    "Scott",
    "Scripps-Booth",
    "Seagrave",
    "Sebring",
    "Sebring-Vanguard",
    "Seeley",
    "Seibt",
    "Sendling",
    "Serenissima",
    "Sertum",
    "Serveta Lambretta",
    "Shadow",
    "Shamrock",
    "Shay",
    "Shelby",
    "Shelby American",
    "Sheldonhurst",
    "Sherco",
    "Sherpley",
    "Shirley",
    "Siata",
    "Siata-Ford",
    "Sicra",
    "Silk",
    "Silnes-Offenhauser Tomshe",
    "Sima-Violet",
    "Simca",
    "Simca Fiat",
    "Simonini",
    "Simplex",
    "Simplex Crane",
    "Simplex Manufacturing Corporation",
    "Simpson",
    "Simson",
    "Sin Cars",
    "Singer",
    "Siva",
    "Sizaire-Berwick",
    "Skoda",
    "Smart",
    "Snowberger Offenhauser",
    "Solex",
    "Solo",
    "Southern Roadcraft",
    "Sovam",
    "Soyer",
    "Spada",
    "Spania GTA Spano",
    "Sparta",
    "Spartan",
    "Spartan Cars",
    "Sparton",
    "Speedwell",
    "Spice",
    "Spirit",
    "Spitaler",
    "Spyker",
    "Squire",
    "Squire Car Manufacturing Company",
    "Ssangyong",
    "Standard",
    "Stanley",
    "Stanley Motor Carriage Company",
    "Star",
    "Steadman",
    "Stearns-Knight",
    "Steffey",
    "Steib",
    "Steinherr",
    "Steinwinter",
    "Sterckeman",
    "Sterling Autocycle",
    "Sterling Motor Cars",
    "Sterzi",
    "Stevens-Duryea",
    "Stewart & Stevenson",
    "Steyr",
    "Steyr-Daimler-Puch",
    "Steyr-Fiat",
    "Steyr-Opel",
    "Steyr-Puch",
    "Stihl",
    "Stock",
    "Stoewer",
    "Stola",
    "Straker-Squire",
    "Strohm",
    "Studebaker",
    "Stutz",
    "Styl'son",
    "Subaru",
    "Suecia",
    "Suffolk",
    "Sulzer",
    "Sunbeam",
    "Sunbeam Cycles",
    "Sunbeam-Talbot",
    "Suncar",
    "Super Aguri",
    "Superformance",
    "Superlite",
    "Surrey",
    "Surtees",
    "Suzuki",
    "Swallow",
    "Swallow Doretti",
    "Swift",
    "Sylva",
    "Symbol",
    "Sénéchal",
    "T.E.C.",
    "TGM",
    "TM Racing",
    "TRK",
    "TVR",
    "TWS",
    "Tabbert",
    "Talbot",
    "Talbot-Lago",
    "Talbot-Matra",
    "Tanesini",
    "Tarpan",
    "Tatra",
    "Taurus",
    "Taylor-Dunn",
    "Teal",
    "Tecno",
    "Tecnomoto",
    "Teledyne Continental Cheetah",
    "Templar",
    "Tempo",
    "Terradyne",
    "Terraplane",
    "Terrot",
    "Tesla",
    "Tesserault",
    "Testi",
    "Tettner",
    "The Boeing Company",
    "The Detroit Electric",
    "The Famous James",
    "The H.H. Babcock Company",
    "The Henney Motor Company",
    "The Scott Motorcycle Company",
    "Thomann",
    "Thomas B. Jeffery Company",
    "Thomas Motor Company",
    "Thor",
    "Thornycroft",
    "Thoroughbred",
    "Thunder Ranch",
    "Thurner",
    "Tiga",
    "Timeless",
    "Titan",
    "ToJ",
    "Tofas",
    "Tojeiro",
    "Tojeiro-Climax",
    "Tomaszo",
    "Tomos",
    "Toreador",
    "Tornado",
    "Tornax",
    "Torpedo",
    "Touring Superleggera",
    "Toyota",
    "Trabant",
    "Trawo",
    "Treser",
    "TriBSA",
    "Tribute",
    "Trident",
    "Trigano",
    "Triking",
    "Triple C",
    "Triple E",
    "Tritan Ventures",
    "Triton",
    "Triumph",
    "Triumph (TWN)",
    "Triumph Motorcycles",
    "Trojan",
    "Tröller",
    "Tucker 48",
    "Tuk-Tuk",
    "Turismo",
    "Turner",
    "Turrinelli",
    "Twin Coach",
    "Tyrrell",
    "UAZ",
    "UMM",
    "URS",
    "UT",
    "Ultima",
    "Unic",
    "Unipower",
    "Unique Autocraft",
    "Unitrak",
    "Universal",
    "Ural",
    "Ursus",
    "Urus",
    "VEB Gartenbautechnik",
    "VELAM",
    "VM",
    "VOMAG",
    "VOR",
    "Valiant",
    "Van Diemen",
    "Van Grinsven",
    "Van Veen",
    "Vanclee",
    "Vanden Plas",
    "Vanderhall",
    "Vanguard",
    "Vanwall",
    "Vauxhall",
    "Vector",
    "Velocette",
    "Velorex",
    "Veloto",
    "Venom",
    "Venturi",
    "Veritas",
    "Verona",
    "Vespa",
    "Victor",
    "Victoria",
    "Victory",
    "Villa",
    "Villiers",
    "Vincent",
    "Vintage Speedsters",
    "Vixen",
    "Volkswagen",
    "Volpini",
    "Volugrafo",
    "Volvo",
    "Voxan",
    "Vulcan",
    "Vyatka",
    "Vyrus",
    "VéloSoleX",
    "W.A.M.",
    "WASP Yahama",
    "WFM",
    "WK",
    "Wahl",
    "Wall",
    "Walz",
    "Wanderer",
    "Warchalowski",
    "Warszawa",
    "Wartburg",
    "Warwick",
    "WaterCar",
    "Watsonian",
    "Waverley",
    "Weferlinger Heimstolz",
    "Weineck",
    "Weippert",
    "Werner",
    "Wesseler",
    "Westcott Motor Car Company",
    "Western Flyer",
    "Westfalia",
    "Westfield",
    "Whippet",
    "White",
    "White Motor Company",
    "Whizzer",
    "Wiesmann",
    "Wilk",
    "Williams",
    "Williams & Pritchard",
    "Wills Sainte Claire",
    "Willys",
    "Willys-Knight",
    "Willys-Overland",
    "Willys-Viasa",
    "Wimmer",
    "Windhoff",
    "Wingfield",
    "Winnebago",
    "Winton",
    "Witte",
    "Wittek",
    "Wlost",
    "Wolf",
    "Wolf Racing Cars",
    "Wolfbart",
    "Wolga",
    "Wolseley",
    "Wolseley-Siddeley",
    "Würdig",
    "XP",
    "XT3",
    "Yamaha",
    "Yugo",
    "Zagato",
    "Zakspeed",
    "Zastava",
    "Zato",
    "Zedel",
    "Zenith",
    "Zenos",
    "Zerchot",
    "Zero Engineering",
    "Zetor",
    "Zettelmeyer",
    "Zhong Shen",
    "ZiL",
    "Zichner",
    "Ziegler",
    "Zimmer",
    "Zundapp",
    "Zytek",
    "Česká Zbrojovka Strakonice",
    "Čezeta",
    "Infiniti"
];


export async function processClearMarqueList() {
    let finalList = [];

    for (const message of requestMessageList) {
        const response = await chatGptHelper.createCompletion(message);

        let parsedArray;

        try {
            parsedArray = JSON.parse(response);
        } catch (e) {
            console.log(response);
            parsedArray = [];
        }

        finalList.push(...parsedArray);
    }

    return finalList;
}

export async function filterNonMarqueNamesFromListBatchPreparer(req: Request) {
    const marketsCollectionName = 'markets';

    const topLevelMarketNodeList = await dataCrudService.queryAllAvailableNodes(req, marketsCollectionName, {
        query: {
            path: {'$size': 1},
            _fields: {
                fullName: 1,
            },
        },
    });

    const existingMarqueList = topLevelMarketNodeList.map(i => i.fullName.toLowerCase());

    const listOfNewPossibleMarqueList = marqueList.filter(i => existingMarqueList.indexOf(i.toLowerCase()) === -1);

    const batchRequestList = listOfNewPossibleMarqueList
        .map((name, index) => prepareCheckNameTypeBatchRequestItem(name, index));

    await storeBatchFile(batchRequestList, 'filter-non-marque-names.jsonl');
}

export async function processFilterNonMarqueNamesFromListBatchResult() {
    const batchOutputFilePath = join('src', 'cars', 'fixing-scripts', '.tmp', 'filter-non-marque-names_output.jsonl');

    const batchOutputFileContent = (await readFile(batchOutputFilePath, 'utf8')).toString();

    const batchOutputItemList = batchOutputFileContent.split('\n').filter(i => !!i).map(i => JSON.parse(i));

    const marqueTokenToNameMap = getMarqueTokenToNameMap();

    const responseList = batchOutputItemList
        .map(i => ({name: marqueTokenToNameMap[i?.custom_id.split('@')[1]], response: i?.response?.body.choices?.[0]?.message?.content}));

    const nameToTypeMap = responseList
        .map(({name, response}) => ({name, type: (parseFilterNonMarqueNameResponse(response) ?? {})?.type}));

    return nameToTypeMap.filter(i => i.type === 'Marque');
}

export async function importMarquesToDatabase(req: Request) {
    const collectionName = 'markets';

    const marqueList = (await processFilterNonMarqueNamesFromListBatchResult())
        .map(i => i.name);

    for (const marque of marqueList) {
        const existingMarque = await dataCrudService.querySingleNode(req, collectionName, {
            query: {fullName: marque},
        });

        if (!!existingMarque) {
            console.log(`processed ${marqueList.indexOf(marque) + 1} of ${marqueList.length}`);

            continue;
        }

        const doc = nodeSystemDataHelper.getUniqueID();
        const slug = marque.toLowerCase().replace(' ', '-');

        const node = {
            _doc: doc,
            fullName: marque,
            name: marque,
            type: 'Marque',
            years: [],
            path: [
                {
                    name: marque,
                    slug: slug,
                    id: doc,
                },
            ],
            metadata: {
                slugToken: slug,
                parentSlugPathReverse: [],
                parentSlugPath: [],
            },
            isActive: true,
        }

        await dataCrudService.createNode(req, collectionName, node);

        console.log(`processed ${marqueList.indexOf(marque) + 1} of ${marqueList.length}`);
    }
}

function prepareCheckNameTypeBatchRequestItem(name: string, index: number) {
    const messageParts = [
        `Is "${name}" recognized as a Marque in the vehicle industry (particularly in the classic vehicle market), `,
        `specifically as a brand under which vehicles are marketed and commonly recognized by consumers? `,
        ` Please confirm the answer based on reputable sources such as automotive history databases, brand websites, `,
        `or Wikipedia. Ensure you cross-reference many authoritative sources to validate the classification. `,
        `If applicable, clarify if "${name}" is instead a manufacturer, sub-brand, or another type of automotive entity.`,
        '\n',
        `Provide your response in the following JSON format: `,
        `{type: "{{value}}"} where value is either "Marque" or whatever else best defines "${name}".`,
    ];

    const message = messageParts.join('');

    const batchId = index.toString() + '@' + prepareMarqueNameToken(name);

    return prepareCompletionBatchItem(message, batchId);
}

function prepareMarqueNameToken(name: string): string {
    return name.toLowerCase().replace(' ', '#');
}

function getMarqueTokenToNameMap() {
    const map: Record<string, string> = {};

    for (const name of marqueList) {
        map[prepareMarqueNameToken(name)] = name;
    }

    return map;
}

function parseFilterNonMarqueNameResponse(response: string) {
    const regexPattern = /```json[\n ](\{(.|\n)+\})[\n ]```/;

    const execResult = regexPattern.exec(response);

    if (!execResult) {
        try {
            return JSON.parse(response.replace('{type:', '{"type":'));
        } catch (e) {
            return null;
        }
    }

    const [match, group] = execResult;

    try {
        return JSON.parse(group.replace('{type:', '{"type":'));
    } catch (e) {
        return null;
    }
}


