name: Documentation Maintenance

on:
  push:
    paths:
      - 'server/**'
      - 'pages/**'
      - 'components/**'
      - 'composables/**'
      - 'middleware/**'
      - 'types/**'
  pull_request:
    types: [opened, synchronize]

jobs:
  update-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Check Documentation Freshness
        id: check-docs
        run: |
          npm run check-docs
          echo "::set-output name=needs_update::$?"

      - name: Create Documentation PR
        if: steps.check-docs.outputs.needs_update == '1'
        uses: peter-evans/create-pull-request@v5
        with:
          title: '📚 Documentation Update Required'
          body: |
            Documentation needs to be updated based on recent code changes.
            
            Please review the following files:
            - [ ] Check interfaces match implementation
            - [ ] Verify architectural documentation is current
            - [ ] Update relevant examples
          branch: docs-update
          commit-message: 'docs: Update documentation based on code changes'
          labels: documentation
